Azure/autorest.typescript

package.json
src/azure/Templates/AzureMethodGroupTemplate.cshtml
src/azure/Templates/AzureServiceClientTemplate.cshtml
src/vanilla/ClientModelExtensions.cs
src/vanilla/Model/CodeModelTS.cs
src/vanilla/Model/MethodGroupTS.cs
src/vanilla/Model/MethodTS.cs
src/vanilla/Model/PrimaryTypeTS.cs
src/vanilla/Templates/MethodGroupTemplate.cshtml
src/vanilla/Templates/ServiceClientTemplate.cshtml
test/vanilla/acceptanceTests.ts
test/vanilla/generated/BodyFile/operations/files.ts
test/vanilla/generated/BodyFormData/operations/formdata.ts

Stream types

---

package.json
src/vanilla/ClientModelExtensions.cs
test/azure/generated/Paging/models/index.ts
test/azure/generated/Paging/models/mappers.ts
test/azure/generated/Paging/operations/paging.ts

Resolves https://github.com/Azure/autorest.typescript/issues/145.

Remove isStream() check

---

.scripts/dependencies.js
README.md
package.json
src/azure/Model/CodeModelTSa.cs

Resolves https://github.com/Azure/autorest.typescript/issues/135

Add deleteFolder() in dependencies.js

---

src/DSL/TSObject.cs
src/vanilla/ClientModelExtensions.cs
test/azure/generated/AzureCompositeModelClient/models/mappers.ts
test/azure/generated/AzureResource/models/mappers.ts
test/azure/generated/Lro/models/mappers.ts
test/azure/generated/StorageManagementClient/models/mappers.ts
test/vanilla/generated/BodyComplex/models/mappers.ts
test/vanilla/generated/Http/models/mappers.ts
test/vanilla/generated/ModelFlattening/models/mappers.ts

Compose mappers

---

.gitmodules
.gulp/gulpfile.iced
README.md
autorest.typescript.sln
package.json
src/autorest.typescript.csproj

Use AutoRest.common as a submodule

---

src/vanilla/Model/MethodTS.cs
test/azure/generated/AzureCompositeModelClient/azureCompositeModel.ts
test/azure/generated/AzureCompositeModelClient/operations/arrayModel.ts
test/azure/generated/AzureCompositeModelClient/operations/basicOperations.ts
test/azure/generated/AzureCompositeModelClient/operations/dictionary.ts
test/azure/generated/AzureCompositeModelClient/operations/primitive.ts
test/azure/generated/AzureCompositeModelClient/operations/readonlyproperty.ts
test/azure/generated/AzureParameterGrouping/operations/parameterGrouping.ts
test/azure/generated/AzureSpecials/operations/apiVersionLocal.ts
test/azure/generated/AzureSpecials/operations/header.ts
test/azure/generated/AzureSpecials/operations/skipUrlEncoding.ts
test/azure/generated/Lro/operations/lROs.ts
test/azure/generated/Paging/operations/paging.ts
test/azure/generated/StorageManagementClient/operations/storageAccounts.ts
test/vanilla/generated/BodyComplex/operations/basicOperations.ts
test/vanilla/generated/ComplexModelClient/complexModelClient.ts
test/vanilla/generated/Url/operations/paths.ts
test/vanilla/generated/Url/operations/queries.ts
test/vanilla/generated/Validation/autoRestValidationTest.ts
test/xml/generated/Xml/operations/xml.ts

Resolves https://github.com/Azure/autorest.typescript/issues/187.

Stop creating variables to storage constant arguments

---

src/vanilla/ClientModelExtensions.cs

Needs manual testing
Related to Azure/ms-rest-js#159

Support x-nullable

---

package.json
src/vanilla/Model/CompositeTypeTS.cs
test/vanilla/acceptanceTests.ts
test/xml/generated/Xml/models/mappers.ts
test/xml/xmlTests.ts

Don't emit xmlName for headers mappers

---

.travis.yml

re-enabling travis CI in the hopes of getting faster feedback on PRs.

Add sudo: required in .travis.yml

---

package.json
src/vanilla/ClientModelExtensions.cs
test/xml/generated/Xml/autoRestSwaggerBATXMLServiceContext.ts
test/xml/generated/Xml/models/mappers.ts
test/xml/generated/Xml/operations/xml.ts
test/xml/xmlTests.ts

Xml properties

---

README.md
package.json
src/vanilla/Model/CodeModelTS.cs
test/vanilla/acceptanceTests.ts

Just updating a test to demonstrate things work end-to-end.

Test progress callbacks in node

---

src/vanilla/ClientModelExtensions.cs

Fix bug related to null serializedName

---

package.json

Resolves #199.
Reduces arm-network generation time on my laptop from 1:40 to 1:20.

Publish release builds

---

src/DSL/TSObjectType.cs
src/vanilla/Model/CompositeTypeTS.cs
src/vanilla/Model/MethodTS.cs
src/vanilla/TransformerTS.cs
test/azure/generated/AzureCompositeModelClient/models/index.ts
test/azure/generated/AzureResource/models/index.ts
test/azure/generated/AzureSpecials/models/index.ts
test/azure/generated/Lro/models/index.ts
test/azure/generated/Paging/models/index.ts
test/azure/generated/StorageManagementClient/models/index.ts
test/azure/generated/SubscriptionIdApiVersion/models/index.ts
test/azuremetadata/generated/lib/models/index.ts
test/enumunion/generated/BodyString/models/index.ts
test/metadata/generated/lib/models/index.ts
test/no-client-validation/generated/Validation/models/index.ts
test/vanilla/generated/BodyComplex/models/index.ts
test/vanilla/generated/BodyString/models/index.ts
test/vanilla/generated/ComplexModelClient/models/index.ts
test/vanilla/generated/Header/models/index.ts
test/vanilla/generated/Http/models/index.ts
test/vanilla/generated/ModelFlattening/models/index.ts
test/vanilla/generated/RequiredOptional/models/index.ts
test/vanilla/generated/Validation/models/index.ts
test/xml/generated/Xml/models/index.ts

Readonly doc

---

src/vanilla/ClientModelExtensions.cs
unittests/Models.cs
unittests/vanilla/ClientModelExtensionsTests.cs

Missed a possible source for the xmlName value.

Add xmlPrefix to xmlNames from properties

---

src/DSL/TSBlock.cs
src/DSL/TSBuilder.cs
src/DSL/TSIfBlock.cs
src/DSL/TSTryBlock.cs
src/azure/Model/CodeModelTSa.cs
src/azure/Templates/AzureReadmeTemplate.cshtml
src/vanilla/Model/CodeModelTS.cs
src/vanilla/Templates/ReadmeTemplate.cshtml
test/azuremetadata/generated/Lro/README.md
test/metadata/generated/BodyComplex/README.md
test/multiapi/packages/multiapi-test-2017-10-01/README.md
test/multiapi/packages/multiapi-test-2018-02-01/README.md
test/multiapi/packages/multiapi-test/README.md
unittests/DSL/TSBuilderTests.cs
unittests/vanilla/Model/CodeModelTSTests.cs

Resolves https://github.com/Azure/autorest.typescript/issues/252.

Fix generated samples

---

src/DSL/TSBuilder.cs
src/DSL/TSDocumentationComment.cs
src/vanilla/Model/MethodTS.cs
test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
test/multiapi/packages/multiapi-test/package-lock.json
unittests/DSL/TSDocumentationCommentTests.cs
unittests/Models.cs

Resolves https://github.com/Azure/autorest.typescript/issues/356.

Add deprecated method support

---

src/vanilla/GeneratorSettingsTS.cs

Resolves https://github.com/Azure/autorest.typescript/issues/372.

Remove -preview suffix from generated package versions

---

.gulp/gulpfile.iced
.gulp/publishing.iced
package.json

Resolves https://github.com/Azure/autorest.typescript/issues/388.

Remove previous publishing strategy and update version to 2.1.0

---

package.json
src/azure/Model/CodeModelTSa.cs
src/vanilla/ClientModelExtensions.cs
src/vanilla/Model/CodeModelTS.cs
src/vanilla/Templates/TsConfig.cshtml
test/azuremetadata/generated/Lro/package.json
test/azuremetadata/generated/Lro/tsconfig.json
test/custom-service-client-options/generated/Xml/package.json
test/custom-service-client-options/generated/Xml/tsconfig.json
test/metadata/generated/BodyComplex/package.json
test/metadata/generated/BodyComplex/tsconfig.json
test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
test/multiapi/packages/multiapi-test-2017-10-01/package.json
test/multiapi/packages/multiapi-test-2017-10-01/tsconfig.json
test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
test/multiapi/packages/multiapi-test-2018-02-01/package.json
test/multiapi/packages/multiapi-test-2018-02-01/tsconfig.json
test/multiapi/packages/multiapi-test/package-lock.json
test/multiapi/packages/multiapi-test/package.json
test/multiapi/packages/multiapi-test/tsconfig.json
test/skip-subtypes/generated/BodyComplex/package.json
test/skip-subtypes/generated/BodyComplex/tsconfig.json
test/unit-tests-custom/generated/BodyString/package.json
test/unit-tests-custom/generated/BodyString/tsconfig.json
test/unit-tests-mocha/generated/BodyString/package.json
test/unit-tests-mocha/generated/BodyString/tsconfig.json
test/vanilla/generated/XMSErrorResponses/models/mappers.ts

- Serialization bug fix for polymorphic models
- updated ms-rest-js and ms-rest-azure-js versions in generated package.json
- added "dom" to "lib" in tsconfig.json

multiple fixes

---

test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
test/multiapi/packages/multiapi-test/package-lock.json

This change updates the `package-lock.json` files in the `multiapi` test packages so that installation doesn't fail with errors about out-of-sync `package-lock.json` files when running in CI.

Update package-lock.json in multiapi test packages

---

package-lock.json
package.json
src/generators/mappersGenerator.ts
src/transforms/mapperTransforms.ts
src/transforms/operationTransforms.ts
src/typescriptGenerator.ts
test/integration/bodyComplex.spec.ts
test/integration/generated/bodyComplex/src/models/mappers.ts
test/integration/generated/bodyComplex/src/operations/array.ts
test/integration/generated/bodyComplex/src/operations/basic.ts
test/integration/generated/bodyComplex/src/operations/dictionary.ts
test/integration/generated/bodyComplex/src/operations/flattencomplex.ts
test/integration/generated/bodyComplex/src/operations/inheritance.ts
test/integration/generated/bodyComplex/src/operations/polymorphicrecursive.ts
test/integration/generated/bodyComplex/src/operations/polymorphism.ts
test/integration/generated/bodyComplex/src/operations/primitive.ts
test/integration/generated/bodyComplex/src/operations/readonlyproperty.ts
test/integration/generated/bodyString/src/models/mappers.ts
test/integration/generated/bodyString/src/operations/enum.ts
test/integration/generated/bodyString/src/operations/string.ts
test/unit/transforms/mapperTransforms.spec.ts

Changes to handle complex schemas and pass all BodyComplex tests.
Also switching to prettier printWidth=80 to match default value
@daviwil I'd like to hear if you have any better ideas on how to handle additionaProperties, since I'm not sure that is the right/scalable way

[v6] Full BodyComplex

---

package-lock.json
package.json
src/vanilla/Model/CodeModelTS.cs
test/azuremetadata/generated/Lro/LICENSE.txt
test/custom-service-client-options/generated/Xml/LICENSE.txt
test/multiapi/packages/multiapi-test-2017-10-01/LICENSE.txt
test/multiapi/packages/multiapi-test-2018-02-01/LICENSE.txt
test/multiapi/packages/multiapi-test/LICENSE.txt
test/skip-subtypes/generated/BodyComplex/LICENSE.txt
test/unit-tests-custom/generated/BodyString/LICENSE.txt
test/unit-tests-mocha/generated/BodyString/LICENSE.txt
test/vanilla/generated/CompositeBoolIntClient/LICENSE.txt

[v4x] Fix naming issue with x-ms-code-generation-settings name

---

test/azuremetadata/generated/Lro/LICENSE.txt
test/custom-service-client-options/generated/Xml/LICENSE.txt
test/multiapi/packages/multiapi-test-2017-10-01/LICENSE.txt
test/multiapi/packages/multiapi-test-2018-02-01/LICENSE.txt
test/multiapi/packages/multiapi-test/LICENSE.txt
test/skip-subtypes/generated/BodyComplex/LICENSE.txt
test/unit-tests-custom/generated/BodyString/LICENSE.txt
test/unit-tests-mocha/generated/BodyString/LICENSE.txt
test/vanilla/generated/CompositeBoolIntClient/LICENSE.txt

Updating license dates to fix the build

Update license date

---

src/generators/modelsGenerator.ts

[v6] only use request media types when writing optional parameters

---

.scripts/ci.yml
package.json
test/integration/generated/mediaTypesV3Lro/src/mediaTypesV3LROClient.ts
test/integration/generated/mediaTypesV3Lro/src/models/parameters.ts
test/utils/check-clean-tree.ts

Add a check for a clean git tree to make sure no un-intended changes in generated clients slip through

[v6] Check git tree on CI

---

.scripts/build.yml
.scripts/ci.yml
test/integration/noMappers.spec.ts

**Problem**
CI build was failing silently because one step had 2 scripts. Turns out that the pipeline would just take the exit code of the last script to run, in linux ([ref](https://github.com/Microsoft/azure-pipelines-tasks/issues/10125#issuecomment-484014918)). Thanks @chradek for figuring this out 😄
**Fix**
- Move git tree check to its own step
- Fix the failing test

[v6] Fix failing ci

---

test/integration/bodyDictionary.spec.ts

[v6] Add missing dictionary tests

---

.gitignore
.scripts/checkEverything.ts
.scripts/checkPackageJsonVersion.ts
.scripts/releasePipeline.sh
azure-pipelines.yml
package.json

Changes to run in the new Pipeline:
* Explicitly indicate PR triggers
* Used to be a GUI override
* Publish package.json to artifacts, in order to simplify publishing script.
* Disable package version check
* Add releaseTag

New pipeline

---

src/generators/operationGenerator.ts

[v6] Explicitly check operationGroup for JSON content and set default

---

src/generators/operationGenerator.ts
src/utils/extractHeaders.ts

A couple of errors surfaced when generating service bus. There are 2 problems:
* Failing to correctly detect xmlSerializer
* Not generating header mappers for Exception/Error responses

[v6] Extract headers for Exceptions

---

.github/CODEOWNERS

Adding deyaaeldeen to code owners

---

src/vanilla/Model/CodeModelTS.cs
test/azuremetadata/generated/Lro/README.md
test/custom-service-client-options/generated/Xml/README.md
test/metadata/generated/BodyComplex/README.md
test/multiapi/packages/multiapi-test-2017-10-01/README.md
test/multiapi/packages/multiapi-test-2018-02-01/README.md
test/multiapi/packages/multiapi-test/README.md
test/skip-subtypes/generated/BodyComplex/README.md
test/unit-tests-custom/generated/BodyString/README.md
test/unit-tests-mocha/generated/BodyString/README.md

Adding Auth information to README

---

package-lock.json
package.json
src/azure/Model/CodeModelTSa.cs
src/vanilla/Model/CodeModelTS.cs
test/azuremetadata/generated/Lro/README.md
test/custom-service-client-options/generated/Xml/README.md
test/metadata/generated/BodyComplex/README.md
test/multiapi/packages/multiapi-test-2017-10-01/README.md
test/multiapi/packages/multiapi-test-2018-02-01/README.md
test/multiapi/packages/multiapi-test/README.md
test/skip-subtypes/generated/BodyComplex/README.md
test/unit-tests-custom/generated/BodyString/README.md
test/unit-tests-mocha/generated/BodyString/README.md

@joheredi please regenerate the readme files again :)

Reword the authentication section in the generated README.md files

---

test/integration/bodyArray.spec.ts

This PR is to address the issue https://github.com/Azure/autorest.typescript/issues/750 
@joheredi  Please review and approve

Add coverage for missing body-array test server scenarios

---

test/integration/bodyDateTime.spec.ts

Fixes https://github.com/Azure/autorest.typescript/issues/751.

adding a missing test to body-datetime

---

docs/contributing.md
docs/overview.md

Adding documentation for project design overview and contributing information

[v6] Add project overview and contributing documentation

---

src/generators/clientFileGenerator.ts
test/unit/generators/clientFileGenerator.spec.ts

This PR is to fix the issue with Issue: https://github.com/Azure/autorest.typescript/issues/738
@joheredi Please review and approve

Added code to avoid name collisions

---

package-lock.json
package.json
src/generators/clientContextFileGenerator.ts
src/models/clientDetails.ts
src/transforms/optionsTransforms.ts
test/integration/azureSpecialProperties.spec.ts
test/integration/generated/azureSpecialProperties/src/azureSpecialPropertiesClientContext.ts
test/unit/transforms/optionsTransforms.spec.ts
test/utils/test-swagger-gen.ts

Support passing credential-scopes in CLI and passing it over to the ServiceClient for authentication

Support credential-scopes

---

src/vanilla/Model/CodeModelTS.cs
test/azuremetadata/generated/Lro/README.md
test/custom-service-client-options/generated/Xml/README.md
test/metadata/generated/BodyComplex/README.md
test/multiapi/packages/multiapi-test-2017-10-01/README.md
test/multiapi/packages/multiapi-test-2018-02-01/README.md
test/multiapi/packages/multiapi-test/README.md
test/skip-subtypes/generated/BodyComplex/README.md
test/unit-tests-custom/generated/BodyString/README.md
test/unit-tests-mocha/generated/BodyString/README.md

Implements @ramya-rao-a's suggestions here: https://github.com/Azure/azure-sdk-for-js/pull/13512.

[V4] Add a note to README files that older credentials are supported

---

test/integration/httpInfrastructure.spec.ts

To remove some skips from HttpInfrastructure Spec file

Remove Skips from HttpInfrastructure Spec

---

src/autorestSession.ts
src/utils/autorestOptions.ts
test/integration/generated/readmeFileChecker/src/keyVaultClient.ts
test/integration/generated/readmeFileChecker/src/keyVaultClientContext.ts
test/utils/run.ts
test/utils/smoke-test.ts
test/utils/test-swagger-gen.ts

To be shared between integration tests and smoke tests. @sarangan12 helped with plumbing extra params to the command.

Refactor autorest run command

---

package-lock.json
src/generators/static/apiExtractorConfig.ts
src/generators/static/packageFileGenerator.ts
src/generators/static/tsConfigFileGenerator.ts
src/main.ts
src/restLevelClient/config.ts
src/restLevelClient/generateRestLevel.ts
test/integration/generated/bodyStringRest/LICENSE.txt
test/integration/generated/bodyStringRest/api-extractor.json
test/integration/generated/bodyStringRest/package.json
test/integration/generated/bodyStringRest/tsconfig.json
test/utils/run.ts
test/utils/test-swagger-gen.ts

Generating static files for REST Level Client

Generate static files for REST Level Clients

---

package-lock.json
package.json

prepare for release for 4.6

---

package-lock.json
package.json

Which generate readmes that have the updated support policy.

Prepare for 4.7 release

---

CHANGELOG.md
package-lock.json
package.json

This PR is to Update package version & Changelog to 6.0.0-beta.4 for the next preview release of @autorest/typescript.
@joheredi @deyaaeldeen Please review and approve.
@ramya-rao-a FYI....

Update package version & Changelog to 6.0.0-beta.4

---

CHANGELOG.md
package-lock.json
package.json

This PR is to Update package version & Changelog to 6.0.0-beta.4 for the next preview release of @autorest/typescript.
@joheredi @deyaaeldeen @dw511214992  Please review and approve.
@ramya-rao-a FYI....

Update package version & Changelog to 6.0.0-beta.5

---

CONTRIBUTING.md

This is the initial version of the Contributing.md file that would be helpful for anyone who would like to contribute to our project. 
@dw511214992 @ramya-rao-a Please review and share your thoughts.

Initial Version of the Contributing.md

---

CHANGELOG.md
package-lock.json
package.json

This PR is to update the version and changelog for the 6.0.0-beta.6 release. 
@deyaaeldeen @dw511214992 Please review and approve. 
@ramya-rao-a FYI

Release changes for 6.0.0-beta.6

---

CHANGELOG.md
package-lock.json
package.json

Release SDK Generator 6.0.0-beta.8

Release SDK Generator 6.0.0-beta.8

---

.scripts/ci.yml
.scripts/release.yml

This PR is to Enable Nightly Builds for SDK Generator Project

Enable Nightly Builds for SDK Generator Project

---

.scripts/release.yml

Update Github Publishing Name

---

src/generators/static/tsConfigFileGenerator.ts
test/integration/generated/bodyComplexRest/tsconfig.json
test/integration/generated/bodyStringRest/tsconfig.json
test/integration/generated/multipleInheritanceRest/tsconfig.json

llc tsconfig missed a dist-esm change accordingly due to pr #1123

fix llc dist esm in tsconfig

---

package-lock.json
package.json

Windows does not recognize the `cp src/generators/static/README.md.hbs dist/src/generators/static/README.md.hbs` command. The package [copyfiles](https://www.npmjs.com/package/copyfiles) fixes this and the command was changed to `copyfiles src/generators/static/README.md.hbs dist/src/generators/static/README.md.hbs`.

Adding "copyfiles" package

---

src/generators/static/README.md.hbs
test/integration/generated/iotspaces/README.md
test/integration/generated/iotspaces/package.json
test/utils/test-swagger-gen.ts

Addressing issue https://github.com/Azure/autorest.typescript/issues/1138.

Linking guide on how to create an Azure AD application in the Readme

---

src/generators/static/README.md.hbs
src/generators/static/packageFileGenerator.ts
src/generators/static/readmeFileGenerator.ts
test/integration/generated/iotspaces/README.md
test/integration/generated/lro/package.json
test/integration/generated/lroParametrizedEndpoints/package.json
test/integration/generated/mediaTypesV3Lro/package.json
test/integration/generated/nameChecker/README.md
test/integration/generated/paging/package.json
test/integration/generated/pagingNoIterators/package.json
test/integration/generated/readmeFileChecker/README.md
test/smoke/generated/arm-package-deploymentscripts-2019-10-preview/package.json
test/smoke/generated/arm-package-managedapplications-2018-06/package.json
test/smoke/generated/arm-package-resources-2019-08/package.json
test/smoke/generated/compute-resource-manager/package.json
test/smoke/generated/cosmos-db-resource-manager/package.json
test/smoke/generated/keyvault-resource-manager/package.json
test/smoke/generated/network-resource-manager/package.json
test/smoke/generated/sql-resource-manager/package.json
test/smoke/generated/storage-resource-manager/package.json
test/smoke/generated/web-resource-manager/package.json

bump-core-lro-and-fix-readme-link

---

src/generators/static/README.md.hbs
test/integration/generated/iotspaces/README.md

Addressing [Ramya's comment](https://github.com/Azure/autorest.typescript/pull/1146#discussion_r686373306).
Deleting the `en-us` locale from the readme.

Remove locale from readme

---

src/transforms/mapperTransforms.ts
test/integration/generated/textanalytics/src/models/parameters.ts
test/smoke/generated/compute-resource-manager/src/models/mappers.ts
test/smoke/generated/compute-resource-manager/src/models/parameters.ts
test/smoke/generated/keyvault-resource-manager/src/models/mappers.ts
test/smoke/generated/network-resource-manager/src/models/mappers.ts
test/smoke/generated/sql-resource-manager/src/models/mappers.ts
test/smoke/generated/web-resource-manager/src/models/mappers.ts

Fixing issue: https://github.com/Azure/autorest.typescript/issues/1120

Fixing bug in Boolean parameters with false default value

---

CHANGELOG.md
package-lock.json
package.json

Release 6.0.0-beta.9 version

---

CHANGELOG.md
package-lock.json
package.json

Release Beta 10 Changes

---

CHANGELOG.md
package-lock.json
package.json

Fixes https://github.com/Azure/autorest.typescript/issues/1179

Release Beta 12 Changes

---

CHANGELOG.md
package-lock.json
package.json
test/smoke/generated/agrifood-data-plane/temp/agrifood-data-plane.api.json
test/smoke/generated/agrifood-data-plane/types/tsdoc-metadata.json

This PR updates the changelog and package.json files for releasing the Beta 13 version of the SDK Generator. 
@joheredi @JonathanCrd Please review and approve the PR.

Release Beta 13 Changes

---

CHANGELOG.md
package-lock.json
package.json

Version Update and Changelog Update for Beta 14 release

Version Update and Changelog

---

CHANGELOG.md
package-lock.json
package.json

Release 6.0.0-beta.15 version of TS Generator

Release 6.0.0-beta.15 version of TS Generator

---

CHANGELOG.md
package-lock.json
package.json
src/autorestSession.ts
src/conflictResolver.ts
src/main.ts
src/restLevelClient/generateObjectTypes.ts
src/restLevelClient/generateRestLevel.ts
src/transforms/transforms.ts
src/typescriptGenerator.ts
src/utils/autorestOptions.ts
test/unit/transforms/optionsTransforms.spec.ts

Recently there was a breaking change introduced in @autorest/extension-base without a major version bump. This change updates the code to align with the latest API. Most of the changes are on method name casing and the shape of writeFile parameters

Fix breaking changes from M4

---

README.md
test/azuremetadata/generated/Lro/LICENSE.txt
test/custom-service-client-options/generated/Xml/LICENSE.txt
test/multiapi/packages/multiapi-test-2017-10-01/LICENSE.txt
test/multiapi/packages/multiapi-test-2018-02-01/LICENSE.txt
test/multiapi/packages/multiapi-test/LICENSE.txt
test/skip-subtypes/generated/BodyComplex/LICENSE.txt
test/unit-tests-custom/generated/BodyString/LICENSE.txt
test/unit-tests-mocha/generated/BodyString/LICENSE.txt
test/vanilla/generated/CompositeBoolIntClient/LICENSE.txt

This PR updates the development section of the main Readme for v4.
It adds more information on how to get the proper development environment by installing older versions of Node and Dotnet and provides insights on common errors or problems.
Let me know if you think that this section should be its own `CONTRIBUTING.md` file.

[Readme][v4] Update Development section and License year

---

CHANGELOG.md
package-lock.json
package.json
src/restLevelClient/generateRestLevel.ts
test/utils/smoke-test-list.ts

to resolve issue https://github.com/azure/autorest.typescript/issues/1334 and release a newer version of typescript for a few bugfixes

clear generated output folder for rlc and bump a new beta version

---

karma.conf.js
package-lock.json
package.json
test/utils/smoke-test.ts

Audit Fixes III for @autorest/typescript package

Audit Fixes III for @autorest/typescript package

---

src/generators/static/packageFileGenerator.ts
test/integration/generated/additionalProperties/package.json
test/integration/generated/datasearch/package.json
test/rlcIntegration/generated/bodyStringRest/package.json
test/smoke/generated/agrifood-data-plane/package.json
test/smoke/generated/compute-resource-manager/package.json
test/smoke/generated/keyvault-resource-manager/package.json
test/smoke/generated/msi-resource-manager/package.json
test/smoke/generated/network-resource-manager/package.json
test/smoke/generated/sql-resource-manager/package.json
test/smoke/generated/storage-resource-manager/package.json
test/smoke/generated/web-resource-manager/package.json

Fix the two libs missing issue  both in RLC and HLC gen
- chai 
- @types/chai

Add chai and @types/chai in code gen

---

src/utils/autorestOptions.ts

Add MICROSOFT_MIT_NO_VERSION  by default

Default license to true

---

CHANGELOG.md
package-lock.json
package.json

To release a 6.0.0-rc.1 for rlc GA

release 6.0.0-rc.1 for rlc ga

---

src/generators/static/packageFileGenerator.ts
test/commands/smoke-test-list.ts
test/rlcIntegration/generated/bodyComplexRest/package.json
test/rlcIntegration/generated/bodyFileRest/package.json
test/rlcIntegration/generated/bodyFormDataRest/package.json
test/rlcIntegration/generated/bodyStringRest/package.json
test/rlcIntegration/generated/customUrlRest/package.json
test/rlcIntegration/generated/dpgCustomization/package.json
test/rlcIntegration/generated/headerRest/package.json
test/rlcIntegration/generated/httpInfrastructureRest/package.json
test/rlcIntegration/generated/lroRest/package.json
test/rlcIntegration/generated/mediaTypesRest/package.json
test/rlcIntegration/generated/multipleInheritanceRest/package.json
test/rlcIntegration/generated/pagingRest/package.json
test/rlcIntegration/generated/urlRest/package.json
test/smoke/generated/agrifood-data-plane/package.json
test/smoke/generated/purview-administration-rest/package.json

change code generator accordingly with this change https://github.com/Azure/azure-sdk-for-js/commit/83e13d88f985a8808530efe9d2e6c10ef12fb2e3

update eslint version for rlc

---

src/restLevelClient/generateObjectTypes.ts
test/rlcIntegration/bodyComplextRest.spec.ts
test/rlcIntegration/generated/bodyComplexRest/src/models.ts
test/rlcIntegration/generated/bodyComplexRest/src/outputModels.ts
test/smoke/generated/agrifood-data-plane/review/agrifood-data-plane.api.md
test/smoke/generated/agrifood-data-plane/src/models.ts
test/smoke/generated/agrifood-data-plane/src/outputModels.ts
test/smoke/generated/synapse-artifacts-rest/src/models.ts
test/smoke/generated/synapse-artifacts-rest/src/outputModels.ts

fix https://github.com/Azure/autorest.typescript/issues/1437

Try fix polymorphism base class duplicate name issue

---

src/transforms/samplesTransforms.ts

This PR is trying to resolve issues like this 
we should just import the element type

fix-array-type-payload

---

test/commands/test-swagger-gen.ts
test/rlcIntegration/generated/securityAADRest/.eslintrc.json
test/rlcIntegration/generated/securityAADRest/LICENSE
test/rlcIntegration/generated/securityAADRest/README.md
test/rlcIntegration/generated/securityAADRest/api-extractor.json
test/rlcIntegration/generated/securityAADRest/package.json
test/rlcIntegration/generated/securityAADRest/src/clientDefinitions.ts
test/rlcIntegration/generated/securityAADRest/src/index.ts
test/rlcIntegration/generated/securityAADRest/src/isUnexpected.ts
test/rlcIntegration/generated/securityAADRest/src/parameters.ts
test/rlcIntegration/generated/securityAADRest/src/responses.ts
test/rlcIntegration/generated/securityAADRest/src/securityAADRestClient.ts
test/rlcIntegration/generated/securityAADRest/tsconfig.json
test/rlcIntegration/generated/securityKeyRest/.eslintrc.json
test/rlcIntegration/generated/securityKeyRest/LICENSE
test/rlcIntegration/generated/securityKeyRest/README.md
test/rlcIntegration/generated/securityKeyRest/api-extractor.json
test/rlcIntegration/generated/securityKeyRest/package.json
test/rlcIntegration/generated/securityKeyRest/src/clientDefinitions.ts
test/rlcIntegration/generated/securityKeyRest/src/index.ts
test/rlcIntegration/generated/securityKeyRest/src/isUnexpected.ts
test/rlcIntegration/generated/securityKeyRest/src/parameters.ts
test/rlcIntegration/generated/securityKeyRest/src/responses.ts
test/rlcIntegration/generated/securityKeyRest/src/securityKeyRestClient.ts
test/rlcIntegration/generated/securityKeyRest/tsconfig.json
test/rlcIntegration/securityAadRest.spec.ts
test/rlcIntegration/securityKeyRest.spec.ts

fix https://github.com/Azure/autorest.typescript/issues/1414

add-test-coverage-for-security-add-and-security-key

---

package-lock.json
package.json
src/transforms/mapperTransforms.ts
src/transforms/operationTransforms.ts
test/unit/transforms/operationTransforms.spec.ts

There exists issue when handling Binary schema, we'll fix them in this pr

Binary support fix

---

packages/cadl-rlc-emitter/src/modelUtils.ts
packages/cadl-rlc-test/test/authoring/cadl-output/review/authoring.api.md
packages/cadl-rlc-test/test/authoring/cadl-output/src/outputModels.ts

fix dictionary type in cadl emitter

---

packages/cadl-rlc-emitter/package.json
packages/cadl-rlc-emitter/src/modelUtils.ts
packages/cadl-rlc-emitter/src/transform/transformSchemas.ts
packages/cadl-rlc-emitter/test/integration/generated/models/inheritance/src/models.ts
packages/cadl-rlc-emitter/test/integration/generated/models/inheritance/src/outputModels.ts
packages/cadl-rlc-emitter/test/integration/generated/models/primitiveProperties/src/models.ts
packages/cadl-rlc-emitter/test/unit/generate/docs.spec.ts
packages/cadl-rlc-emitter/test/unit/generate/models.spec.ts

Fix model type unit test

---

packages/cadl-rlc-emitter/src/operationUtil.ts
packages/cadl-rlc-emitter/src/paramUtil.ts
packages/cadl-rlc-emitter/src/transform/transformParameters.ts
packages/cadl-rlc-emitter/src/transform/transformPaths.ts
packages/cadl-rlc-emitter/test/integration/generated/resiliency/devDriven/src/clientDefinitions.ts
packages/cadl-rlc-emitter/test/integration/generated/resiliency/devDriven/src/parameters.ts
packages/cadl-rlc-emitter/test/unit/generate/docs.spec.ts
packages/cadl-rlc-emitter/test/unit/generate/parameters.spec.ts
packages/cadl-rlc-test/test/authoring/cadl-output/review/authoring.api.md
packages/cadl-rlc-test/test/authoring/cadl-output/src/clientDefinitions.ts
packages/cadl-rlc-test/test/authoring/cadl-output/src/parameters.ts
packages/cadl-rlc-test/test/confidentialLedger/cadl-output/review/confidential-ledger.api.md
packages/cadl-rlc-test/test/confidentialLedger/cadl-output/src/clientDefinitions.ts
packages/cadl-rlc-test/test/confidentialLedger/cadl-output/src/parameters.ts

Filter out api version in parameter due to it is client-level parameter
fixes https://github.com/Azure/autorest.typescript/issues/1539

Filter out api version in parameter

---

packages/cadl-rlc-emitter/src/modelUtils.ts
packages/cadl-rlc-emitter/src/transform/transformParameters.ts
packages/cadl-rlc-emitter/test/integration/generated/extensibleEnums/src/parameters.ts
packages/cadl-rlc-emitter/test/integration/generated/models/propertyTypes/src/models.ts
packages/cadl-rlc-emitter/test/integration/generated/models/propertyTypes/src/outputModels.ts
packages/cadl-rlc-emitter/test/unit/generate/models.spec.ts
packages/cadl-rlc-test/test/authoring/cadl-output/review/authoring.api.md
packages/cadl-rlc-test/test/authoring/cadl-output/src/models.ts
packages/cadl-rlc-test/test/authoring/cadl-output/src/outputModels.ts
packages/cadl-rlc-test/test/playfab/cadl-output/review/playfab.api.md
packages/cadl-rlc-test/test/playfab/cadl-output/src/models.ts
packages/cadl-rlc-test/test/playfab/cadl-output/src/outputModels.ts

Add possible values into doc for extensible enum
fixes https://github.com/Azure/autorest.typescript/issues/1524

Add possible values into doc for extensible enum

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/package.json
packages/autorest.typescript/test/rlcIntegration/bodyFormDataRest.spec.ts
packages/autorest.typescript/test/utils/stream-helpers.browser.ts
packages/autorest.typescript/test/utils/stream-helpers.ts
packages/autorest.typescript/webpack.config.test.js

fixes https://github.com/Azure/autorest.typescript/issues/1481

Fix binary bugfix

---

packages/autorest.typescript/test/commands/smoke-test-list.ts
packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/urlRest/src/isUnexpected.ts
packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/src/isUnexpected.ts
packages/autorest.typescript/test/smoke/generated/purview-administration-rest/src/account/isUnexpected.ts
packages/autorest.typescript/test/smoke/generated/purview-administration-rest/src/metadataPolicies/isUnexpected.ts
packages/autorest.typescript/test/smoke/generated/synapse-artifacts-rest/src/isUnexpected.ts
packages/cadl-rlc-emitter/test/integration/generated/resiliency/devDriven/src/isUnexpected.ts
packages/cadl-rlc-test/test/authoring/cadl-output/src/isUnexpected.ts
packages/cadl-rlc-test/test/confidentialLedger/cadl-output/src/isUnexpected.ts
packages/rlc-codegen/src/buildIsUnexpectedHelper.ts

Fix isunexpted helper issue

---

.scripts/ci.yml
.scripts/release.yml
packages/autorest.typescript/CHANGELOG.md
packages/autorest.typescript/package.json
packages/cadl-typescript/CHANGELOG.md
packages/rlc-common/CHANGELOG.md

try-to-make-release-pipeline-work

---

packages/autorest.typescript/package.json
packages/cadl-rlc-test/package.json
packages/cadl-typescript/CHANGELOG.md
packages/cadl-typescript/package.json
packages/rlc-common/CHANGELOG.md
packages/rlc-common/package.json

fix this error https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1920340&view=logs&j=6e6cd934-b249-5120-4299-21f24be20cc5&t=e0bef2b5-f3c1-5556-9f29-2e5d53b7a03e

fix-invalid-dev-version

---

packages/cadl-typescript/src/lib.ts
packages/cadl-typescript/src/transform/transform.ts
packages/cadl-typescript/src/transform/transfromRLCOptions.ts
packages/rlc-common/src/interfaces.ts

support-sdk-folder-in-emiiter

---

packages/autorest.typescript/src/generators/static/packageFileGenerator.ts
packages/autorest.typescript/test/integration/generated/additionalProperties/package.json
packages/autorest.typescript/test/integration/generated/datasearch/package.json
packages/autorest.typescript/test/integration/generated/patterntest/package.json
packages/autorest.typescript/test/smoke/generated/compute-resource-manager/package.json
packages/autorest.typescript/test/smoke/generated/keyvault-resource-manager/package.json
packages/autorest.typescript/test/smoke/generated/msi-resource-manager/package.json
packages/autorest.typescript/test/smoke/generated/network-resource-manager/package.json
packages/autorest.typescript/test/smoke/generated/sql-resource-manager/package.json
packages/autorest.typescript/test/smoke/generated/storage-resource-manager/package.json
packages/autorest.typescript/test/smoke/generated/web-resource-manager/package.json
packages/autorest.typescript/test/smoke/generated/web-resource-manager/review/web-resource-manager.api.md

https://github.com/Azure/azure-sdk-for-js/issues/23519

add @types/node in packagefilegenerator.ts

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/package.json
packages/cadl-typescript/package.json

use-stable-core-client-version

---

packages/cadl-typescript/src/operationUtil.ts
packages/cadl-typescript/src/transform/transformParameters.ts
packages/cadl-typescript/test/unit/generate/parameters.spec.ts

fixes https://github.com/Azure/autorest.typescript/issues/1547

Support multiple form data

---

packages/cadl-rlc-test/test/authoring/cadl-project.yaml
packages/cadl-rlc-test/test/confidentialLedger/cadl-project.yaml
packages/cadl-rlc-test/test/playfab/cadl-project.yaml
packages/cadl-typescript/src/transform/transfromRLCOptions.ts
packages/cadl-typescript/test/integration/generated/authentication/apiKey/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/authentication/oauth2/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/clients/interfaces/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/dictionary/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/extensibleEnums/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/hello/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/lro/lroBasic/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/models/inheritance/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/models/propertyOptional/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/models/propertyTypes/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/models/readonlyProperties/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/models/usage/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/resiliency/devDriven/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/resiliency/srvDriven1/cadl-project.yaml
packages/cadl-typescript/test/integration/generated/resiliency/srvDriven2/cadl-project.yaml

Fix the option azureSdkForJs in cadl gen

Fix the option azureSdkForJs in cadl gen

---

packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/src/clientDefinitions.ts
packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/src/multipleUrlParameterRestClient.ts
packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/src/parameters.ts
packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/src/responses.ts
packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/urlRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/multipleUrlParameterRest.spec.ts
packages/autorest.typescript/test/rlcIntegration/swaggers/multipleUrlParameter.json
packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/src/isUnexpected.ts
packages/autorest.typescript/test/smoke/generated/anomaly-detector-rest/src/isUnexpected.ts
packages/autorest.typescript/test/smoke/generated/purview-administration-rest/src/account/isUnexpected.ts
packages/autorest.typescript/test/smoke/generated/purview-administration-rest/src/metadataPolicies/isUnexpected.ts
packages/autorest.typescript/test/smoke/generated/synapse-artifacts-rest/src/isUnexpected.ts
packages/cadl-rlc-test/test/authoring/cadl-output/src/isUnexpected.ts
packages/cadl-rlc-test/test/confidentialLedger/cadl-output/src/isUnexpected.ts
packages/cadl-typescript/test/integration/generated/resiliency/devDriven/src/isUnexpected.ts
packages/rlc-common/src/buildIsUnexpectedHelper.ts

fixes https://github.com/Azure/autorest.typescript/issues/1513

Fix is unexpected helper

---

packages/autorest.typescript/src/generators/utils/parameterUtils.ts
packages/autorest.typescript/test/integration/generated/nameChecker/src/operations/documents.ts
packages/autorest.typescript/test/integration/generated/nameChecker/src/operationsInterfaces/documents.ts
packages/autorest.typescript/test/smoke/generated/compute-resource-manager/review/compute-resource-manager.api.md
packages/autorest.typescript/test/smoke/generated/compute-resource-manager/src/operations/virtualMachineExtensionImages.ts
packages/autorest.typescript/test/smoke/generated/compute-resource-manager/src/operationsInterfaces/virtualMachineExtensionImages.ts
packages/autorest.typescript/test/smoke/generated/sql-resource-manager/src/operations/syncGroups.ts

fixes https://github.com/Azure/autorest.typescript/issues/1529

fix-hlc-parameter-order-issue

---

packages/autorest.typescript/src/utils/valueHelpers.ts
packages/autorest.typescript/test/smoke/generated/compute-resource-manager/samples-dev/availabilitySetsListBySubscriptionSample.ts
packages/autorest.typescript/test/smoke/generated/compute-resource-manager/samples-dev/galleryApplicationVersionsCreateOrUpdateSample.ts
packages/autorest.typescript/test/smoke/generated/compute-resource-manager/samples-dev/galleryApplicationVersionsUpdateSample.ts
packages/autorest.typescript/test/smoke/generated/network-resource-manager/samples-dev/packetCapturesCreateSample.ts

fix-mgmt-sample-generation-special-charactor

---

packages/autorest.typescript/src/generators/modelsGenerator.ts
packages/autorest.typescript/src/transforms/parameterTransforms.ts
packages/autorest.typescript/test/integration/generated/azureParameterGrouping/src/models/parameters.ts
packages/autorest.typescript/test/integration/generated/azureParameterGrouping/src/operations/parameterGrouping.ts
packages/autorest.typescript/test/unit/transforms/parameterTransforms.spec.ts

fixes https://github.com/Azure/autorest.typescript/issues/1677 
refer https://github.com/Azure/autorest.typescript/pull/1346

fix-parameter-rename-in-options

---

packages/cadl-typescript/test/integration/fixedEnums.spec.ts

fixes https://github.com/Azure/autorest.typescript/issues/1712

Fixed enum test cases

---

packages/cadl-typescript/src/index.ts
packages/rlc-common/src/buildTopLevelIndexFile.ts
packages/rlc-common/src/helpers/pathUtils.ts

fix-path-separator-issue

---

packages/autorest.typescript/src/utils/valueHelpers.ts
packages/autorest.typescript/test/integration/generated/corecompattest/src/models/parameters.ts
packages/autorest.typescript/test/integration/generated/petstore/src/models/parameters.ts
packages/autorest.typescript/test/integration/petstore.spec.ts
packages/autorest.typescript/test/integration/swaggers/petstore.json

fixes https://github.com/Azure/autorest.typescript/issues/1601

Fix the default value for array

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/CHANGELOG.md
packages/autorest.typescript/package.json
packages/rlc-common/CHANGELOG.md
packages/rlc-common/package.json
packages/typespec-test/package.json
packages/typespec-ts/CHANGELOG.md
packages/typespec-ts/package.json

fixes https://github.com/Azure/autorest.typescript/issues/1774

Bump the verson for typespec

---

packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/models.ts
packages/typespec-ts/src/index.ts
packages/typespec-ts/src/modular/emitModels.ts
packages/typespec-ts/src/modular/helpers/getType.ts

This PR adds support for generating models

[Modular Client] Generate models

---

packages/typespec-ts/test/commands/cadl-ranch-list.ts
packages/typespec-ts/test/integration/generated/projection/src/clientDefinitions.ts
packages/typespec-ts/test/integration/generated/projection/src/index.ts
packages/typespec-ts/test/integration/generated/projection/src/models.ts
packages/typespec-ts/test/integration/generated/projection/src/parameters.ts
packages/typespec-ts/test/integration/generated/projection/src/projectionClient.ts
packages/typespec-ts/test/integration/generated/projection/src/responses.ts
packages/typespec-ts/test/integration/generated/projection/tspconfig.yaml
packages/typespec-ts/test/integration/projection.spec.ts

add-projection-cadl-ranch-test

---

packages/autorest.typescript/CHANGELOG.md
packages/autorest.typescript/package.json

fixes https://github.com/Azure/autorest.typescript/issues/1631

GA-autorest-typescript-v6

---

common/config/rush/pnpm-lock.yaml
packages/typespec-ts/package.json
packages/typespec-ts/test/integration/collectionFormat.spec.ts
packages/typespec-ts/test/integration/dictionary.spec.ts
packages/typespec-ts/test/integration/modelPropertyNullable.spec.ts
packages/typespec-ts/test/integration/projection.spec.ts

fixes https://github.com/Azure/autorest.typescript/issues/1800

Support nullable cases

---

packages/typespec-ts/test/commands/cadl-ranch-list.ts
packages/typespec-ts/test/integration/generated/internal/src/clientDefinitions.ts
packages/typespec-ts/test/integration/generated/internal/src/index.ts
packages/typespec-ts/test/integration/generated/internal/src/internalClient.ts
packages/typespec-ts/test/integration/generated/internal/src/models.ts
packages/typespec-ts/test/integration/generated/internal/src/outputModels.ts
packages/typespec-ts/test/integration/generated/internal/src/parameters.ts
packages/typespec-ts/test/integration/generated/internal/src/responses.ts
packages/typespec-ts/test/integration/generated/internal/tspconfig.yaml
packages/typespec-ts/test/integration/internal.spec.ts

add-internal-cadl-ranch-test-case

---

.scripts/ci.yml

`pnpm` command is not working in ci environment. we need to switch to `common/scripts/install-run-rush-pnpm.js` script.

update the ci

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/CHANGELOG.md
packages/autorest.typescript/package.json
packages/rlc-common/CHANGELOG.md
packages/rlc-common/package.json
packages/typespec-test/package.json
packages/typespec-ts/CHANGELOG.md
packages/typespec-ts/package.json

Bump the version for June release

Bump the version for June release

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/CHANGELOG.md
packages/autorest.typescript/package.json
packages/autorest.typescript/test/rlcIntegration/generated/bodyComplexRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/bodyFileRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/bodyFormDataRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/bodyStringRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/customUrlRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/headerRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/httpInfrastructureRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/lroRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/mediaTypesRest/src/isUnexpected.ts
packages/autorest.typescript/test/rlcIntegration/generated/multipleInheritanceRest/src/isUnexpected.ts
packages/rlc-common/CHANGELOG.md
packages/rlc-common/package.json
packages/rlc-common/src/buildIsUnexpectedHelper.ts
packages/typespec-test/package.json
packages/typespec-test/test/healthinsight/generated/typespec-ts/src/isUnexpected.ts
packages/typespec-test/test/parametrizedHost/generated/typespec-ts/src/isUnexpected.ts
packages/typespec-test/test/translator/generated/typespec-ts/src/isUnexpected.ts
packages/typespec-ts/CHANGELOG.md
packages/typespec-ts/package.json

fix the healthinsight isUnexpected helper issue.

fix-is-unexpected-helper-in-healthinsight

---

packages/typespec-test/test/loadTest/generated/openapi/2022-11-01/openapi.json
packages/typespec-test/test/loadTest/generated/typespec-ts/review/load-testing.api.md
packages/typespec-test/test/loadTest/generated/typespec-ts/src/clientDefinitions.ts
packages/typespec-test/test/loadTest/generated/typespec-ts/src/isUnexpected.ts
packages/typespec-test/test/loadTest/generated/typespec-ts/src/models.ts
packages/typespec-test/test/loadTest/generated/typespec-ts/src/outputModels.ts
packages/typespec-test/test/loadTest/generated/typespec-ts/src/parameters.ts
packages/typespec-test/test/loadTest/generated/typespec-ts/src/pollingHelper.ts
packages/typespec-test/test/loadTest/generated/typespec-ts/src/responses.ts
packages/typespec-test/test/loadTest/spec/client.tsp
packages/typespec-test/test/loadTest/spec/models.tsp
packages/typespec-test/test/loadTest/spec/routes.tsp
packages/typespec-ts/README.md

Update json renaming in client.tsp with @@projectedName decorator for load testing service.

Update load testing service with projected name

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/CHANGELOG.md
packages/autorest.typescript/package.json
packages/rlc-common/CHANGELOG.md
packages/rlc-common/package.json
packages/typespec-test/package.json
packages/typespec-ts/CHANGELOG.md
packages/typespec-ts/package.json
packages/typespec-ts/src/modular/buildCodeModel.ts

Bump the compiler version for July fixes

Bump the emitter version for July fixes

---

packages/rlc-common/src/interfaces.ts
packages/rlc-common/src/metadata/buildPackageFile.ts
packages/rlc-common/src/metadata/buildReadmeFile.ts
packages/typespec-ts/src/index.ts
packages/typespec-ts/src/lib.ts

fixes https://github.com/microsoft/typespec/issues/2148

Export lib to index.ts so that compiler could know the options schema

---

packages/autorest.typescript/test/rlcIntegration/generated/bodyStringRest/package.json
packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/package.json
packages/autorest.typescript/test/smoke/generated/anomaly-detector-rest/package.json
packages/rlc-common/src/metadata/buildPackageFile.ts
packages/typespec-test/test/anomalyDetector/generated/typespec-ts/package.json
packages/typespec-test/test/authoring/generated/typespec-ts/package.json
packages/typespec-test/test/batch/generated/typespec-ts/package.json
packages/typespec-test/test/batch_modular/generated/typespec-ts/package.json
packages/typespec-test/test/collectionFormat/generated/typespec-ts/package.json
packages/typespec-test/test/confidentialLedger/generated/typespec-ts/package.json
packages/typespec-test/test/contoso/generated/typespec-ts/package.json
packages/typespec-test/test/customWrapper/generated/typespec-ts/package.json
packages/typespec-test/test/eventgrid_modular/generated/typespec-ts/package-files/package.json
packages/typespec-test/test/healthinsight/generated/typespec-ts/package.json
packages/typespec-test/test/loadTest/generated/typespec-ts/package.json
packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/package-files/package.json
packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/package.json
packages/typespec-test/test/openai/generated/typespec-ts/package.json
packages/typespec-test/test/openai_modular/generated/typespec-ts/package-files/package.json
packages/typespec-test/test/translator/generated/typespec-ts/package.json
packages/typespec-test/test/widget_dpg/generated/typespec-ts/package-files/package.json
packages/typespec-ts/src/modular/buildProjectFiles.ts
packages/typespec-ts/test/integration/generated/authentication/apiKey/package.json

- upgrade dev dependency `karma-firefox-launcher` version to `^2.1.2`
- update test baseline

Upgrade `karma-firefox-launcher` version to `^2.1.2`

---

packages/autorest.typescript/src/generators/static/hlcREADME.md.hbs
packages/autorest.typescript/src/generators/static/readmeFileGenerator.ts
packages/autorest.typescript/src/typescriptGenerator.ts

fixes https://github.com/Azure/autorest.typescript/issues/1388
Add a boolean value to the metadata to determine whether the subscription id needs to be added to the client example in readme.md

fix the parameter issue of client example in readme

---

.scripts/ci.yml
common/config/rush/pnpm-lock.yaml
packages/rlc-common/package.json
packages/rlc-common/src/buildClient.ts
packages/rlc-common/src/buildIsUnexpectedHelper.ts
packages/rlc-common/src/buildPaginateHelper.ts
packages/rlc-common/src/buildPollingHelper.ts
packages/rlc-common/src/buildSerializeHelper.ts
packages/rlc-common/src/helpers/operationHelpers.ts
packages/rlc-common/src/metadata/buildApiExtractorConfig.ts
packages/rlc-common/src/metadata/buildESLintConfig.ts
packages/rlc-common/src/metadata/buildLicenseFile.ts
packages/rlc-common/src/metadata/buildPackageFile.ts
packages/rlc-common/src/metadata/buildReadmeFile.ts
packages/rlc-common/src/metadata/buildTsConfig.ts
packages/rlc-common/src/test/buildEnvFile.ts
packages/rlc-common/src/test/buildKarmaConfig.ts
packages/rlc-common/src/test/buildRecordedClient.ts
packages/rlc-common/src/test/buildSampleTest.ts

see comment here https://github.com/Azure/autorest.typescript/pull/2002#discussion_r1326789213

Update the format and lint rules

---

.scripts/ci.yml
.vscode/launch.json
common/config/rush/pnpm-lock.yaml
packages/rlc-common/CONTRIBUTING.md
packages/rlc-common/package.json
packages/rlc-common/test/helpers/nameUtils.spec.ts

see comment here: https://github.com/Azure/autorest.typescript/pull/2002#discussion_r1326778024

Enable UT for rlc-common project

---

packages/typespec-test/test/loadTest/generated/typespec-ts/review/load-testing.api.md
packages/typespec-test/test/loadTest/generated/typespec-ts/src/models.ts
packages/typespec-test/test/loadTest/generated/typespec-ts/src/parameters.ts
packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/rest/models.ts
packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/rest/parameters.ts
packages/typespec-ts/src/utils/modelUtils.ts
packages/typespec-ts/test/unit/modelsGenerator.spec.ts
packages/typespec-ts/test/unit/parametersGenerator.spec.ts

fix https://github.com/Azure/azure-sdk-for-js/pull/27087#issuecomment-1720020323

fix-offset-datetime-in-rlc

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/CHANGELOG.md
packages/autorest.typescript/package.json
packages/rlc-common/CHANGELOG.md
packages/rlc-common/package.json
packages/typespec-test/package.json
packages/typespec-ts/CHANGELOG.md
packages/typespec-ts/package.json

Bump a emitter and autorest version

Bump a version to 0.17.0 after upgrading tsp to v0.48

---

common/config/rush/command-line.json
packages/autorest.typescript/package.json
packages/typespec-test/package.json
packages/typespec-ts/package.json

I often found the need to re-generate baselines for almost everything. This PR adds a command to make that easier.

Add a rush command to re-generate baselines

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/package.json
packages/autorest.typescript/test/rlcIntegration/lroRest.spec.ts

JSON parse error messages are now difference between NodeJS and browser so tests are updated.

Upgrade dev dependency puppeteer to ^21.0.0

---

packages/typespec-test/test/chatApi_modular/generated/typespec-ts/src/api/operations.ts
packages/typespec-test/test/openai_modular/generated/typespec-ts/src/api/operations.ts
packages/typespec-ts/src/modular/helpers/operationHelpers.ts
packages/typespec-ts/test/modularIntegration/generated/models/inheritance/not-discriminated/src/api/operations.ts
packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts

fixes #1982
partially fix https://github.com/Azure/autorest.typescript/issues/2215 and https://github.com/Azure/autorest.typescript/issues/2217

fix-circular-reference-generation-failure

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/test/commands/test-swagger-gen.ts

fix https://github.com/Azure/autorest.typescript/pull/2165 ci failure

fix ci failure

---

packages/typespec-ts/test/modularIntegration/clientStructureDefault.spec.ts

Fixes https://github.com/Azure/autorest.typescript/issues/2257

Update modular client structure service test case

---

packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/src/serializeHelper.ts
packages/autorest.typescript/test/rlcIntegration/generated/urlRest/src/serializeHelper.ts
packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/src/serializeHelper.ts
packages/rlc-common/src/static/serializeHelper.ts
packages/typespec-test/test/translator/generated/typespec-ts/src/serializeHelper.ts
packages/typespec-test/test/widget_dpg/generated/typespec-ts/sources/generated/src/rest/serializeHelper.ts
packages/typespec-test/test/widget_dpg/generated/typespec-ts/src/rest/serializeHelper.ts
packages/typespec-ts/test/integration/generated/azure/core/src/serializeHelper.ts
packages/typespec-ts/test/integration/generated/encode/bytes/src/serializeHelper.ts
packages/typespec-ts/test/integration/generated/encode/datetime/src/serializeHelper.ts
packages/typespec-ts/test/integration/generated/encode/duration/src/serializeHelper.ts
packages/typespec-ts/test/integration/generated/parameters/collection-format/src/serializeHelper.ts
packages/typespec-ts/test/modularIntegration/generated/azure/core/src/rest/serializeHelper.ts
packages/typespec-ts/test/modularIntegration/generated/encode/bytes/src/rest/serializeHelper.ts
packages/typespec-ts/test/modularIntegration/generated/encode/datetime/src/rest/serializeHelper.ts
packages/typespec-ts/test/modularIntegration/generated/encode/duration/src/rest/serializeHelper.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/collection-format/src/rest/serializeHelper.ts

fix https://github.com/Azure/autorest.typescript/issues/2302

add return type to fix lint error

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/package.json

to fix the pipeline timeout issues

upgrade-puppeteer

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/CHANGELOG.md
packages/autorest.typescript/package.json
packages/rlc-common/CHANGELOG.md
packages/rlc-common/package.json
packages/typespec-test/package.json
packages/typespec-ts/CHANGELOG.md
packages/typespec-ts/package.json

Upgrade the emitter version in April

Upgrade the emitter version in April

---

.scripts/build.yml
.scripts/ci.yml
.scripts/release.yml
.scripts/smoke-test.yml
common/scripts/install-run-rush-pnpm.js
common/scripts/install-run-rush.js
common/scripts/install-run-rushx.js
common/scripts/install-run.js
rush.json

fixes https://github.com/Azure/autorest.typescript/issues/2454
Revert node version and upgrade rush version.

Upgrade rush version to 5.120.6

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/CHANGELOG.md
packages/autorest.typescript/package.json
packages/rlc-common/CHANGELOG.md
packages/rlc-common/package.json
packages/typespec-test/package.json
packages/typespec-ts/CHANGELOG.md
packages/typespec-ts/package.json

Update the changelog and release a new version in late April

Update the changelog and release a new version in late April

---

packages/typespec-ts/src/modular/helpers/typeHelpers.ts
packages/typespec-ts/src/modular/serialization/serializeArray.ts
packages/typespec-ts/src/modular/serialization/serializeDateTime.ts
packages/typespec-ts/src/modular/serialization/serializeHeaders.ts
packages/typespec-ts/src/modular/serialization/serializers.ts
packages/typespec-ts/src/modular/serialization/util.ts
packages/typespec-ts/test-next/integration/serialization/serializeArray.test.ts
packages/typespec-ts/test-next/integration/serialization/serializeDateTime.test.ts
packages/typespec-ts/test-next/integration/serialization/serializeHeaders.test.ts
packages/typespec-ts/test-next/integration/serialization/test-hots.ts
packages/typespec-ts/test-next/unit/serialization/util.test.ts

Moving serialize array to its own file and add tests

Add array serializer and test

---

packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/review/arm-networkanalytics.api.md
packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/src/restorePollerHelpers.ts
packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/review/load-testing.api.md
packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/testRunOperations/restorePollerHelpers.ts
packages/typespec-test/test/widget_dpg/generated/typespec-ts/review/widget_dpg.api.md
packages/typespec-test/test/widget_dpg/generated/typespec-ts/src/restorePollerHelpers.ts
packages/typespec-ts/src/modular/buildLroFiles.ts
packages/typespec-ts/test/modularIntegration/generated/azure/core/lro/rpc/generated/src/restorePollerHelpers.ts
packages/typespec-ts/test/modularIntegration/generated/azure/core/lro/standard/generated/src/restorePollerHelpers.ts

fixes https://github.com/Azure/autorest.typescript/issues/2605

Remove client Context in restorePoller

---

packages/typespec-ts/src/modular/emitModels.ts
packages/typespec-ts/src/utils/importHelper.ts

fix-import-path-issue

---

common/config/rush/pnpm-lock.yaml
packages/autorest.typescript/test/commands/browser.package.json
packages/autorest.typescript/test/rlcIntegration/generated/dpgCustomization/package.json
packages/autorest.typescript/test/rlcIntegration/generated/lroRest/package.json
packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/package.json
packages/autorest.typescript/test/rlcIntegration/package.json
packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/package.json
packages/autorest.typescript/test/smoke/generated/anomaly-detector-rest/package.json
packages/rlc-common/src/metadata/packageJson/azurePackageCommon.ts
packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/package.json
packages/typespec-test/test/authoring/generated/typespec-ts/package.json
packages/typespec-test/test/contoso/generated/typespec-ts/package.json
packages/typespec-test/test/faceai/generated/typespec-ts/package.json
packages/typespec-test/test/healthInsights_radiologyinsights/generated/typespec-ts/package.json
packages/typespec-test/test/healthInsights_trialmatcher/generated/typespec-ts/package.json
packages/typespec-test/test/loadTest/generated/typespec-ts/package.json
packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/package.json
packages/typespec-test/test/openai/generated/typespec-ts/package.json
packages/typespec-test/test/widget_dpg/generated/typespec-ts/package.json
packages/typespec-ts/package.json
packages/typespec-ts/test/integration/generated/azure/core/lro/rpc/package.json
packages/typespec-ts/test/integration/generated/azure/core/lro/standard/package.json
packages/typespec-ts/test/modularIntegration/generated/azure/core/lro/rpc/generated/package.json
packages/typespec-ts/test/modularIntegration/generated/azure/core/lro/standard/generated/package.json

fixes https://github.com/Azure/autorest.typescript/issues/2565

Update the v3 core-lro from preview to stable

---

packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/src/rest/models.ts
packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/src/rest/outputModels.ts
packages/typespec-test/test/authoring/generated/typespec-ts/src/outputModels.ts
packages/typespec-test/test/contoso/generated/typespec-ts/src/outputModels.ts
packages/typespec-test/test/faceai/generated/typespec-ts/src/models.ts
packages/typespec-test/test/faceai/generated/typespec-ts/src/outputModels.ts
packages/typespec-test/test/faceai/generated/typespec-ts/src/parameters.ts
packages/typespec-ts/src/utils/modelUtils.ts
packages/typespec-ts/test/integration/generated/azure/core/basic/src/parameters.ts
packages/typespec-ts/test/integration/generated/azure/core/lro/rpc/src/outputModels.ts
packages/typespec-ts/test/integration/generated/azure/core/lro/standard/src/outputModels.ts
packages/typespec-ts/test/integration/generated/azure/resource-manager/models/resources/src/models.ts
packages/typespec-ts/test/integration/generated/azure/resource-manager/models/resources/src/outputModels.ts
packages/typespec-ts/test/integration/generated/client/naming/src/parameters.ts
packages/typespec-ts/test/integration/generated/type/enum/extensible/src/parameters.ts
packages/typespec-ts/test/integration/generated/type/property/value-types/src/models.ts
packages/typespec-ts/test/integration/generated/type/property/value-types/src/outputModels.ts
packages/typespec-ts/test/modularIntegration/generated/azure/core/basic/src/rest/parameters.ts
packages/typespec-ts/test/modularIntegration/generated/azure/core/lro/rpc/generated/src/rest/outputModels.ts
packages/typespec-ts/test/modularIntegration/generated/azure/core/lro/standard/generated/src/rest/outputModels.ts
packages/typespec-ts/test/modularIntegration/generated/azure/resource-manager/models/resources/src/rest/models.ts
packages/typespec-ts/test/modularIntegration/generated/azure/resource-manager/models/resources/src/rest/outputModels.ts
packages/typespec-ts/test/modularIntegration/generated/client/naming/src/rest/parameters.ts
packages/typespec-ts/test/modularIntegration/generated/type/enum/extensible/src/rest/parameters.ts
packages/typespec-ts/test/modularIntegration/generated/type/property/value-types/generated/src/rest/models.ts
packages/typespec-ts/test/modularIntegration/generated/type/property/value-types/generated/src/rest/outputModels.ts
packages/typespec-ts/test/unit/modelsGenerator.spec.ts

fixes https://github.com/Azure/autorest.typescript/issues/2659

add-enum-description-for-rlc

---

packages/rlc-common/src/metadata/buildReadmeFile.ts
packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/README.md
packages/typespec-test/test/batch_modular/generated/typespec-ts/README.md
packages/typespec-test/test/chatApi_modular/generated/typespec-ts/README.md
packages/typespec-test/test/contentsafety_modular/generated/typespec-ts/README.md
packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/README.md
packages/typespec-ts/test/modularIntegration/generated/azure/resource-manager/models/resources/README.md

fix missing url in readme template

---

packages/typespec-ts/src/modular/buildCodeModel.ts

separate fix from https://github.com/Azure/autorest.typescript/pull/2697/commits/17dafe13eb539d52d4545cf8843bb939e0293146

fix resolve conflicts bug

---

common/config/rush/pnpm-lock.yaml
packages/typespec-ts/package.json
packages/typespec-ts/test/integration/generated/parameters/spread/src/clientDefinitions.ts
packages/typespec-ts/test/integration/generated/parameters/spread/src/models.ts
packages/typespec-ts/test/integration/generated/parameters/spread/src/parameters.ts
packages/typespec-ts/test/integration/generated/parameters/spread/src/responses.ts
packages/typespec-ts/test/integration/spreadParameters.spec.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/api/alias/index.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/api/index.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/classic/alias/index.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/index.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/models/index.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/models/models.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/models/options.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/rest/clientDefinitions.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/rest/models.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/rest/parameters.ts
packages/typespec-ts/test/modularIntegration/generated/parameters/spread/src/rest/responses.ts
packages/typespec-ts/test/modularIntegration/spreadParameters.spec.ts

Supplement test case for spread

---

.scripts/ci.yml
packages/typespec-test/package.json

fixes https://github.com/Azure/autorest.typescript/issues/2723

Enable windows testing

---

common/config/rush/pnpm-lock.yaml

Refresh the lock file

---

packages/typespec-ts/test/modularUnit/scenarios.spec.ts

- Allow for specifying multiple scenarios (multiple `h1` sections) in a single markdown file
- Make scenario parsing logic more robust

Scenario test improvements

---

packages/typespec-ts/test/modularUnit/scenarios/example/example.md

Fixes tests not running properly

Fix example scenario formatting

---

packages/typespec-test/test/openai_modular/spec/models/completions/chat_messages.tsp

Fix nightly CI error with https://github.com/Azure/azure-rest-api-specs/commit/d9bdb6a00e47f00da22932ba700db365ece10b29#diff-da7b63ce21220afb58454dc53dfefe15797dd224bbf712dbda41d86349720714R114

Fix Nightly CI

---

.scripts/nightly.yml

To force a pipeline to run even when there are no code changes.
https://learn.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#running-even-when-there-are-no-code-changes

Config Nightly CI improvement with forcing run

---

packages/rlc-common/src/buildLogger.ts

fixes https://github.com/Azure/autorest.typescript/issues/2842

fix the generation path of logger.ts

---

packages/rlc-common/src/metadata/buildReadmeFile.ts
packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/README.md
packages/typespec-test/test/anomalyDetector/generated/typespec-ts/README.md
packages/typespec-test/test/batch_modular/generated/typespec-ts/README.md
packages/typespec-test/test/chatApi_modular/generated/typespec-ts/README.md
packages/typespec-test/test/contentsafety_modular/generated/typespec-ts/README.md
packages/typespec-test/test/eventgrid_modular/generated/typespec-ts/README.md
packages/typespec-test/test/healthInsights_radiologyinsights/generated/typespec-ts/README.md
packages/typespec-test/test/hierarchy_generic/generated/typespec-ts/README.md
packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/README.md
packages/typespec-test/test/openai_generic/generated/typespec-ts/README.md
packages/typespec-test/test/openai_modular/generated/typespec-ts/README.md
packages/typespec-test/test/overloads_modular/generated/typespec-ts/README.md
packages/typespec-test/test/parametrizedHost/generated/typespec-ts/README.md
packages/typespec-test/test/schemaRegistry/generated/typespec-ts/README.md
packages/typespec-test/test/spread/generated/typespec-ts/README.md
packages/typespec-test/test/widget_dpg/generated/typespec-ts/README.md

Adjust the key link format for modular readme

---

packages/typespec-ts/src/lib.ts
packages/typespec-ts/test/modularUnit/scenarios.spec.ts
packages/typespec-ts/test/modularUnit/scenarios/emptyProject/emptyProject.md

fixes https://github.com/Azure/autorest.typescript/issues/2967

Do not crash for an empty project

---

packages/typespec-test/test/NetworkAnalytics.Management/tspconfig.yaml
packages/typespec-test/test/todo_non_branded/tspconfig.yaml
packages/typespec-ts/src/index.ts
packages/typespec-ts/src/transform/transfromRLCOptions.ts
packages/typespec-ts/test/integration/generated/azure/resource-manager/common-properties/tspconfig.yaml
packages/typespec-ts/test/integration/generated/azure/resource-manager/resources/tspconfig.yaml
packages/typespec-ts/test/nonBrandedIntegration/rlc/generated/models/usage/tspconfig.yaml

Set `isModularLibrary` to `true` for unbranded and mgmt plane

---

packages/typespec-ts/src/modular/emitSamples.ts
packages/typespec-ts/test/modularUnit/scenarios/samples/operations/multipleExamplesInOneFile.md

fixes https://github.com/Azure/autorest.typescript/issues/3060

fix await in multi examples in one file

---

packages/typespec-test/test/NetworkAnalytics.Management/tspconfig.yaml
packages/typespec-ts/src/index.ts
packages/typespec-ts/src/transform/transfromRLCOptions.ts

Enable `generateSample: true` if it is a mgmt package

---

packages/typespec-ts/src/modular/serialization/buildDeserializerFunction.ts
packages/typespec-ts/src/modular/serialization/buildSerializerFunction.ts
packages/typespec-ts/test/modularUnit/scenarios/models/deserialization/discriminatedUnion.md

Fix issue where the emitter tries to reference serializers with the wrong name.

Fix incorrect references to discriminated model serializers

---

packages/autorest.typescript/src/restLevelClient/transforms/transformOptions.ts
packages/autorest.typescript/test/rlcIntegration/generated/dpgCustomization/package.json
packages/autorest.typescript/test/rlcIntegration/generated/httpInfrastructureRest/package.json
packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/package.json
packages/autorest.typescript/test/rlcIntegration/generated/securityAADRest/package.json
packages/autorest.typescript/test/rlcIntegration/generated/securityKeyRest/package.json
packages/rlc-common/src/metadata/buildPackageFile.ts
packages/rlc-common/src/metadata/packageJson/buildAzureMonorepoPackage.ts

fixes https://github.com/Azure/autorest.typescript/issues/3195

Support option for rlc swagger and fix missing dependencies

---

packages/typespec-ts/test/azureIntegration/azureClientGenratorCoreDeserializeEmptyStringAsNull.spec.ts
packages/typespec-ts/test/azureIntegration/generated/azure/client-generator-core/deserialize-empty-string-as-null/.gitignore
packages/typespec-ts/test/azureIntegration/generated/azure/client-generator-core/deserialize-empty-string-as-null/src/index.d.ts
packages/typespec-ts/test/azureIntegration/generated/azure/client-generator-core/deserialize-empty-string-as-null/tspconfig.yaml
packages/typespec-ts/test/azureModularIntegration/azureClientGenratorCoreDeserializeEmptyStringAsNull.spec.ts
packages/typespec-ts/test/azureModularIntegration/generated/azure/client-generator-core/deserialize-empty-string-as-null/.gitignore
packages/typespec-ts/test/azureModularIntegration/generated/azure/client-generator-core/deserialize-empty-string-as-null/src/index.d.ts
packages/typespec-ts/test/azureModularIntegration/generated/azure/client-generator-core/deserialize-empty-string-as-null/tspconfig.yaml
packages/typespec-ts/test/commands/cadl-ranch-list.js

Add case for azure client-generator-core deserialize-empty-string-as-null

---

common/config/rush/pnpm-lock.yaml
packages/typespec-ts/package.json

Upgrade azure-http-specs to cover more scenarios cases

Upgrade azure-http-specs 
