- .vscode/settings.json
- package.json
These config tweaks support using [Mocha Sidebar](https://marketplace.visualstudio.com/items?itemName=maty.vscode-mocha-sidebar) which seems to make the experience of running a particular subset of tests or debugging the tests more pleasant :)
For this to work it's necessary to pop open a terminal, run `npm run start-test-server` and then try to run tests in VSCode.
> Add config to support tests in VSCode

- test/azure/azureCustomBaseUri.ts
Looking over the logic, one realizes that the catch will take the AssertionError produced by assert.fail and let the test pass, giving a false positive. Let's fix the problem by ensuring that the error that is caught is not an AssertionError.
> Fail tests when catching an AssertionError

- src/vanilla/ClientModelExtensions.cs
- src/vanilla/Model/CompositeTypeTS.cs
- test/xml/generated/Xml/models/mappers.ts
While doing work on moving serialization into the HTTP pipeline, I found that xmlName wasn't being set properly in the top level of mappers. These changes should fix that.
> Add missing xmlName property to mappers

- .gulp/gulpfile.iced
VSTS puts in lots of noise characters instead of colors, so I'm turning mocha's colors off for CI.
Note I'm not adding this to `mocha.opts` because I still want a plain old `mocha` invocation to have colors.
> Disable colors in CI output for mocha

- package.json
- src/vanilla/Templates/PackageJson.cshtml
- src/vanilla/Templates/TsConfig.cshtml
- tsconfig.json
- Adds importHelpers: true to the base tsconfig. We don't ship this to users, so it doesn't really matter as much.
- Adds importHelpers: true to tsconfig.json template and tslib to package.json template. This will affect how the user's code bundles. In the ARM network client it seemed to make a pretty negligible difference (0.5% of a 800~ KB bundle). Perhaps the generated code doesn't make as use of as many language features that require helpers to be generated by tsc?
- Changes the target of the base tsconfig.json to es6 to match our tsconfig.json template. What target should we really have here?
> Import helpers

- src/vanilla/Templates/PackageJson.cshtml
Somehow I added a leading dash into this file by accident, and probably since it just looks like a line marker in a git diff it was overlooked. Let's fix it.
> Remove leading dash from PackageJson.cshtml

- .scripts/bundlesize.js
- README.md
- package.json
- src/azure/TransformerTSa.cs
- src/vanilla/Model/CodeModelTS.cs
- test/azure/lro.ts
- test/vanilla/acceptanceTests.ts
This fixes a pathological behavior in the azure-arm generator where generating a network client would take 7+ minutes due to insane amounts of JSON serialization/comparision through IModelType.StructurallyEquals. Now it takes about 1 minute on my PC.
While I was at it I fixed the bundlesize check and fixed some build errors in the tests related to recent ms-rest-js changes.
Fixes #159
> No structural equals

- .gulp/gulpfile.iced
- .vscode/launch.json
- test/azure/generated/Lro/operations/lROs.ts
If we don't add this environment variable (TS_NODE_TYPE_CHECK = "Y"), then when ts-node runs our tests it won't find the const enum values (complains about not being able to find Csv on an undefined value). This problem can be fixed by setting the environment variable before running ts-node (as I've done in this PR), or to get rid of ts-node and just compile the typescript code using tsc. I figured everyone would prefer this route. The only problem is that now running "mocha" from the command line outside of gulp, npm, or vscode won't work unless you've previously set the TS_NODE_TYPE_CHECK environment variable.
> Add TS_NODE_TYPE_CHECK environment variable before automated tests

- src/vanilla/Model/MethodGroupTS.cs
- test/vanilla/acceptanceTests.ts
Fixes #178.
Would like to dive in a little and investigate why the original code resulted in a CloudErrorBody but not the code which generates all mappers using essentially `CodeModel.ModelTypes.Concat(CodeModel.HeaderTypes)`. After we confirm working behavior in some of the main ARM services, we may wish to just merge this as it will prevent our Portal users from needing to manually modify the generated code.
> Don't collect types within an error type

- src/azure/Templates/PageModelTemplate.cshtml
- src/vanilla/ClientModelExtensions.cs
- src/vanilla/Model/CompositeTypeTS.cs
- src/vanilla/Templates/ModelTemplate.cshtml
- test/azure/generated/AzureCompositeModelClient/models/index.ts
- test/azure/generated/AzureCompositeModelClient/operations/flattencomplex.ts
- test/azure/generated/AzureCompositeModelClient/operations/polymorphicrecursive.ts
- test/azure/generated/AzureCompositeModelClient/operations/polymorphism.ts
- test/vanilla/complexTypesTests.ts
- test/vanilla/generated/BodyComplex/models/index.ts
- test/vanilla/generated/BodyComplex/operations/flattencomplex.ts
- test/vanilla/generated/BodyComplex/operations/polymorphicrecursive.ts
- test/vanilla/generated/BodyComplex/operations/polymorphism.ts
Fixes Azure/azure-sdk-for-node#2960
We're not 100% sure this is the approach we want, but we have played with a bunch of different possible representations and this so far seems to have the best editor experience.
> Polymorphic interfaces

- README.md
- package.json
- src/vanilla/ClientModelExtensions.cs
- src/vanilla/Model/EnumTypeTS.cs
- test/azure/generated/CustomBaseUri/operations/paths.ts
- test/azure/generated/Lro/operations/lROs.ts
- test/azure/generated/SubscriptionIdApiVersion/microsoftAzureTestUrlContext.ts
- test/vanilla/acceptanceTests.ts
- test/vanilla/generated/BodyArray/models/index.ts
- test/vanilla/generated/BodyArray/operations/arrayModel.ts
- test/vanilla/generated/BodyBoolean/operations/bool.ts
- test/vanilla/generated/BodyNumber/operations/number.ts
- test/vanilla/generated/BodyString/models/index.ts
- test/vanilla/generated/BodyString/operations/string.ts
- test/vanilla/generated/CompositeBoolIntClient/operations/bool.ts
- test/vanilla/generated/CustomBaseUri/operations/paths.ts
- test/vanilla/generated/CustomBaseUriMoreOptions/operations/paths.ts
Fixes #88 
It's not clear whether updating the modeler helped fix the problem, but I'm doing it anyway as we might as well benefit from whatever other fixes happened along the way.
The key was really in overriding ModelAsStringType and using DeclarationName to reference the model type.
> Model enum as string

- .gulp/gulpfile.iced
This runs `git clean` to remove all the node_modules and build products from the metadata tests (i.e. project generation tests) after install/build.
This prevents a situation where you `npm run local` to use a local ms-rest-js but the metadata test's ms-rest-js version hasn't changed.
I also made the metadata install/build tests run in a distinct phase from any js unit tests because installing node modules while running doesn't seem sound to me.
> Add clean step to metadata test

- test/vanilla/acceptanceTests.ts
- test/vanilla/validationTests.ts
- converted failing tests to async/await form so that we can see the error in the test report, instead of just getting a timeout
- disabled some tests as needed in order to get things passing in certain browsers. With some cases, e.g. the min/max UTC dates, it seems unimportant that one browser gives 9999 and another gives 10000. Nothing we can do about it.
> Skip some tests in other browsers

- .scripts/bundlesize.ts
I found this silently broke when the dependencies script changed, probably because we didn't use the `import` syntax in TypeScript.
This should do the trick, and also succeed at reporting non-webpack errors. `npm i` should be sufficient in this environment as the branches being compared should not depend on any local versions of packages.
> Fix bundle size script

- .gulp/dotnet.iced
- .gulp/gulpfile.iced
- .scripts/tsconfig.json
I recently made some changes to dependencies.ts that broke @RikkiGibson's bundlesize.ts script. This PR makes it so that we run `tsc` against our .scripts folder so that doesn't happen again.
> Add a build step that checks our scripts

- package.json
- src/vanilla/Model/MethodTS.cs
- test/azure/generated/AzureCompositeModelClient/models/index.ts
- test/azure/generated/AzureResource/models/index.ts
- test/azure/generated/AzureSpecials/models/index.ts
- test/azure/generated/Lro/models/index.ts
- test/azure/generated/Paging/models/index.ts
- test/azure/generated/StorageManagementClient/models/index.ts
- test/azure/generated/SubscriptionIdApiVersion/models/index.ts
- test/azure/paging.ts
- test/azuremetadata/generated/lib/models/index.ts
- test/enumunion/generated/BodyString/models/index.ts
- test/metadata/generated/lib/models/index.ts
- test/no-client-validation/generated/Validation/models/index.ts
- test/vanilla/acceptanceTests.ts
- test/vanilla/generated/BodyComplex/models/index.ts
- test/vanilla/generated/BodyString/models/index.ts
- test/vanilla/generated/ComplexModelClient/models/index.ts
- test/vanilla/generated/Header/models/index.ts
- test/vanilla/generated/Http/models/index.ts
- test/vanilla/generated/ModelFlattening/models/index.ts
- test/vanilla/generated/RequiredOptional/models/index.ts
- test/vanilla/generated/Validation/models/index.ts
- test/xml/generated/Xml/models/index.ts
This fixes the flattened body types used for paging by simply intersecting with the body type instead of copying the properties over.
See https://github.com/Azure/autorest.typescript/blob/master/src/azure/Templates/PageModelTemplate.cshtml#L29
These kinds of special cases in generating model interfaces make it seem like it's simpler to just reuse those definitions instead of figuring out how to emit them over again.
I added some paging tests that use the flattened response so that we can properly exercise its behavior.
> Paging fix

- .gulp/gulpfile.iced
- .scripts/bundlesize.ts
- src/azure/CodeGeneratorTSa.cs
- src/vanilla/CodeGeneratorTS.cs
- src/vanilla/Templates/PackageJson.cshtml
- src/vanilla/Templates/TsConfigWebpack.cshtml
- src/vanilla/Templates/WebpackConfig.cshtml
- test/azuremetadata/generated/package.json
- test/azuremetadata/generated/tsconfig.esm.json
- test/azuremetadata/generated/webpack.config.js
- test/metadata/generated/package.json
- test/metadata/generated/tsconfig.esm.json
- test/metadata/generated/webpack.config.js
- test/multiapi/generated/package.json
- test/multiapi/generated/webpack.config.js
- ts-loader doesn't yet support ts projects that use the new project references feature, so instead using the esm outputs as inputs to webpack
- Added a "prepare" script to build the generated project
I really wish I understood why the multiapi case puts the outputs in `./cjs/lib/file.js` and the metadata case puts the outputs in `./cjs/file.js`. I've pretty much overdosed on typescript configuration so I'm just gonna let it be for now.
Metadata tests just tend to bring up corner cases--to test the custom module resolution via the inner package.json files, we have to run an npm install in the multiapi folder before bundling.
> Metadata and bundle size fixes

- src/vanilla/ClientModelExtensions.cs
- test/azure/generated/AzureCompositeModelClient/models/mappers.ts
- test/metadata/generated/BodyComplex/lib/models/mappers.ts
- test/vanilla/acceptanceTests.ts
- test/vanilla/complexTypesTests.ts
- test/vanilla/generated/BodyComplex/models/mappers.ts
Resolves #281 by emitting the polymorphicDiscriminator in any type that contains polymorphic subtypes (i.e. because SmartSalmon exists, put it in Salmon too, not just in Fish)
Will want to make sure there aren't more polymorphism tests to cover.
> Fix polymorphism

- src/vanilla/Model/MethodGroupTS.cs
Resolves #302 
I'm not sure why I decided we shouldn't do this in the first place. It doesn't break any of the test fixtures.
> Collect property types within an error body type

- src/vanilla/Model/CodeModelTS.cs
Fixes service clients without any operations but importing objects (credentials) from ms-rest-js package.
> Fix missing msRest import

- .gitignore
- azure-pipelines.yml
- package-lock.json
- package.json
- test/multiapi/packages/multiapi-test-2017-10-01/package-lock.json
- test/multiapi/packages/multiapi-test-2018-02-01/package-lock.json
- test/multiapi/packages/multiapi-test/package-lock.json
This change helps unblock https://github.com/Azure/ms-rest-js/pull/377 which is currently failing due to a lack of `package-lock.json` files in this repository when testing dependent libraries.  The fix is to remove `package-lock.json` from `.gitignore` and check in the up-to-date `package-lock.json` files that get generated for the corresponding `package.json` files in this repo.
> Use package-lock.json to ensure dependency versions on CI

- .gitignore
- azure-pipelines.yml
- package-lock.json
- package.json
This change pulls changes from #525 into the `v4x` so that they can be used for the dependency check run in the `ms-rest-js` repo's CI pipeline.  The `v4x` branch tracks patch and minor updates to the `4.x` series of releases of `autorest.typescript` which generate code with `ms-rest-js` et al.
> Migrate CI fixes over from master branch

- .scripts/publish-dev-release.yml
- package-lock.json
- package.json
This change renames `@microsoft.azure/autorest.typescript` to `@autorest/typescript` and prepares the repo for shipping development releases to GitHub Releases on every successful commit to `master`.  
The advantage of this release automation is that it allows us to run pre-release versions of `@autorest/typescript` with the regression testing tool against `@autorest/core` and `@autorest/modelerfour`, ensuring that changes to the pipeline or modeler don't break our code generator.  This script is *not hooked up yet*; I'll do that after this PR is merged.
We'll only be publishing dev builds to GitHub Releases (for now) because AutoRest v3 can easily pull a specific version of a version from there without a corresponding npm release.  It will keep our npm page free of confusing version …
> Rename to @autorest/typescript and prepare for dev releases

- .gitignore
- README.md
- src/generators/clientContextFileGenerator.ts
- src/generators/clientFileGenerator.ts
- src/generators/mappersGenerator.ts
- src/generators/modelsGenerator.ts
- src/generators/operationGenerator.ts
- src/generators/parametersGenerator.ts
- src/generators/static/packageFileGenerator.ts
- src/models/clientDetails.ts
- src/models/operationDetails.ts
- src/transforms/constants.ts
- src/transforms/operationTransforms.ts
- src/transforms/parameterTransforms.ts
- src/typescriptGenerator.ts
- test/integration/custom-url.spec.ts
- test/integration/generated/bodyComplex/src/bodyComplexClient.ts
- test/integration/generated/bodyComplex/src/bodyComplexClientContext.ts
- test/integration/generated/bodyComplex/src/operations/flattencomplex.ts
- test/integration/generated/bodyString/src/bodyStringClient.ts
- test/integration/generated/bodyString/src/bodyStringClientContext.ts
- test/integration/generated/customUrl/src/customUrlClient.ts
- test/integration/generated/customUrl/src/customUrlClientContext.ts
- test/integration/generated/url/src/urlClient.ts
- test/integration/generated/url/src/urlClientContext.ts
This PR contains the following work:
- Add operations as client properties when there is only one OperationGroup. Otherwise, keep the current behavior of adding a class for each operation group.
- Support `source-code-folder-path` flag to specify a custom source folder path
> Client Operations

- src/generators/clientContextFileGenerator.ts
- src/generators/clientFileGenerator.ts
- src/generators/operationGenerator.ts
- src/generators/parametersGenerator.ts
- src/generators/utils/parameterUtils.ts
- src/generators/utils/stringUtils.ts
- src/models/parameterDetails.ts
- src/transforms/parameterTransforms.ts
- src/transforms/transforms.ts
- src/typescriptGenerator.ts
- test/integration/generated/bodyComplex/src/bodyComplexClientContext.ts
- test/integration/generated/bodyComplex/src/operations/array.ts
- test/integration/generated/bodyComplex/src/operations/dictionary.ts
- test/integration/generated/bodyComplex/src/operations/inheritance.ts
- test/integration/generated/bodyComplex/src/operations/polymorphicrecursive.ts
- test/integration/generated/bodyComplex/src/operations/polymorphism.ts
- test/integration/generated/bodyComplex/src/operations/primitive.ts
- test/integration/generated/bodyString/src/bodyStringClientContext.ts
- test/integration/generated/bodyString/src/operations/string.ts
- test/integration/generated/customUrl/src/customUrlClientContext.ts
- test/integration/generated/url/src/operations/pathItems.ts
- test/integration/generated/url/src/operations/paths.ts
- test/integration/generated/url/src/operations/queries.ts
- test/integration/generated/url/src/urlClient.ts
- test/integration/generated/url/src/urlClientContext.ts
This PR includes:
- Wrap long comments to maximum width
- Simplify optional parameter handling in ClientContext
- Make credentials parameter a "Synthetic" parameter next to SWAGGER parameters to avoid having special hanlding for it
- Add missing JSDoc to Client, and ClientContext
> Multiple clean up fixes for JSDoc and parameter handling

- README.md
- package.json
- src/generators/mappersGenerator.ts
- src/generators/modelsGenerator.ts
- src/models/modelDetails.ts
- src/transforms/mapperTransforms.ts
- src/transforms/objectTransforms.ts
- src/utils/logger.ts
- test/integration/generated/bodyComplex/src/models/index.ts
- test/integration/generated/bodyComplex/src/models/mappers.ts
- test/integration/generated/bodyString/src/operations/string.ts
- test/integration/generated/url/src/models/parameters.ts
- test/integration/generated/xmlservice/src/models/index.ts
- test/integration/generated/xmlservice/src/models/mappers.ts
- test/integration/generated/xmlservice/src/models/parameters.ts
- test/integration/generated/xmlservice/src/operations/xml.ts
The way we handled PolymorphicDiscriminators broke when consuming latest version of `modelerfour` that now runs `prenamer`.
The fix is to make sure we use the discriminatorValue when building the discriminatorPath/discriminatorIndex.
We were using serializedName to build the discriminatorPath, this serializedName fallsback to the schema name if there is no a serializedName available. We were lucky before since our test scenarios had the same names as discriminatorValue and modelerfour did not format the names, but now `prenamer` does, and we break. The correct way to do this is by using the discriminatorValue
Issue #563 is tracking the work to cleanup other places where we fallback to `languages.default.name`
In order for `@azure/core-http`  to serialize Polymorphic objects, we need to …
> [v6] Fix polymorphic mapping

- package.json
As discussed with @chradek , autorest dashboard will report version based on the version in package.json. This would need to be the actual version of the future autorest.typescript based on m4 in order to be readable in dashboard.
> Update to v6.0.0

- README.md
- src/generators/clientContextFileGenerator.ts
- src/transforms/mapperTransforms.ts
- test/integration/generated/bodyArray/src/models/index.ts
- test/integration/generated/bodyArray/src/models/parameters.ts
- test/integration/generated/bodyArray/src/operations/array.ts
- test/integration/generated/bodyComplex/src/models/parameters.ts
- test/integration/generated/bodyComplex/src/operations/array.ts
- test/integration/generated/bodyComplex/src/operations/dictionary.ts
- test/integration/generated/bodyComplex/src/operations/inheritance.ts
- test/integration/generated/bodyComplex/src/operations/polymorphicrecursive.ts
- test/integration/generated/bodyComplex/src/operations/polymorphism.ts
- test/integration/generated/bodyComplex/src/operations/readonlyproperty.ts
- test/integration/generated/bodyString/src/models/parameters.ts
- test/integration/generated/header/src/models/parameters.ts
- test/integration/generated/header/src/operations/header.ts
- test/integration/generated/url/src/models/index.ts
- test/integration/generated/url/src/models/parameters.ts
- test/integration/generated/url/src/operations/pathItems.ts
- test/integration/generated/url/src/operations/paths.ts
- test/integration/generated/url/src/operations/queries.ts
- test/integration/generated/xmlservice/src/models/mappers.ts
Also updates modelerfour and fixes a bug where ClientContext classes were storing `credentials` in a public member that didn't exist. For now I just created a blacklist to hold parameters that shouldn't be exposed, but I think longer-term we could add a field to `ParameterDetails` to determine which parameters should be exposed on the context.
The credentials fix is needed or else TypeScript won't compile the generated code.
> [v6] respects x-ms-client-name in mappers

- README.md
- src/generators/operationGenerator.ts
- src/transforms/extensions.ts
- test/integration/generated/mediaTypes/src/mediaTypesClient.ts
- test/integration/generated/mediaTypes/src/models/index.ts
- test/integration/generated/mediaTypes/src/models/parameters.ts
- test/integration/mediaType.spec.ts
The updated version of modelerfour does not guarantee the same value for `required` for body parameters.
Previously, we assumed that across media types, body parameters would be either consistently required, or consistently not required. Modelerfour will now always treat binary request bodies as required, even if the request body is modeled as not required in the swagger.
The [media_types.json](https://github.com/Azure/autorest.testserver/blob/75c1296f7123abbbc750067df043970cea95d7f2/swagger/media_types.json#L14-L40) swagger has a good example of this, where the JSON request body parameter is not required.
After these code changes, operation overloads no longer have to have the same parameter ordering, as long as they each have a `contentType` parameter (we set …
> [v6] adds support for operation overloads with non-matching parameters

- package-lock.json
- package.json
- src/lro/bodyPollingStrategy.ts
- src/lro/lroPoller.ts
- src/lro/models.ts
- src/lro/operation.ts
- test/unit/lro/bodyPollingStrategy.spec.ts
Initial implementation of LRO support. This PR includes the outlines for the whole LRO implementation plus the BodyPolling strategy. 
After implementing the rest of the strategies, the plan is to integrate LRO to code generation by including the lro folder in the generated output, and referencing when x-ms-long-running-operation extension is used
Coming up in follow up PRs:
* Azure-AsyncOperation strategy
* Location strategy
* Integrate with Code Generation
> [v6] Implement LRO outline and BodyPolling strategy

- src/generators/operationGenerator.ts
@jeremymeng found an issue where when an operation has overloads, `contentType` is misidentified in the arguments list.
The reason for this is because previously, we were detecting which argument is the contentType by looking at the code model's `operation.requests` array and getting the index from that. However, if all the overloads share parameters, those parameters are on `operation.parameters`. This meant that if a parameter from `operation.parameters` showed up in the overload before the ones in `operation.requests[i].parameters`, the contentType lookup would be incorrect.
In some cases (though I haven't been able to identify when) this actually does occur. For example, in form-recognizer. Interestingly when I tried copying the operation that had an issue in form-recognizer into a …
> [v6] improve contentType detection in overloaded methods

- src/transforms/parameterTransforms.ts
- test/integration/generated/bodyArray/src/models/parameters.ts
- test/integration/generated/bodyArray/src/operations/array.ts
- test/integration/generated/bodyDictionary/src/models/parameters.ts
- test/integration/generated/bodyDictionary/src/operations/dictionary.ts
- test/integration/generated/bodyInteger/src/models/parameters.ts
- test/integration/generated/bodyInteger/src/operations/int.ts
- test/integration/generated/bodyNumber/src/models/parameters.ts
- test/integration/generated/bodyNumber/src/operations/number.ts
- test/integration/generated/header/src/models/parameters.ts
- test/integration/generated/header/src/operations/header.ts
- test/integration/generated/mediaTypesV3/src/models/parameters.ts
- test/integration/generated/mediaTypesV3/src/operations/fooApi.ts
**Problem:**
Some Swaggers would take for ever to generate. For example Network
This is caused by our parameter equality comparison, which uses lodash deep isEqual. The problem is that our ParameterDetails object contains a reference to the raw parameter which can be quite deep, in these cases deep comparison was taking very very long.
The fix is to exclude the parameter property when checking equality. I decided to include rather than exclude the properties to get more control on what gets compared, if in the future some other property is added to ParameterDetails it wouldn't impact the comparison unless specifically included
> [v6] Fix parameter equality check

- README.md
- src/generators/clientFileGenerator.ts
- src/generators/mappersGenerator.ts
- src/generators/modelsGenerator.ts
- src/generators/operationGenerator.ts
- src/generators/utils/responseTypeUtils.ts
- test/smoke/generated/msi-resource-manager/src/models/index.ts
- test/smoke/generated/msi-resource-manager/src/models/mappers.ts
While trying to generate Table Storage swagger, I found that the generator has 2 issues:
1. When there are multiple success responses defined, we'd get duplicate mappers. This is similar to the bug fixed on PR #633. The difference is that in this scenario, the response types are defined inline instead of being references ([see here](https://github.com/Azure/azure-rest-api-specs/blob/f5cb6fb416ae0a06329599db9dc17c8fdd7f95c7/specification/cosmos-db/data-plane/Microsoft.TablesStorage/preview/2019-02-02/table.json#L137))
As in the previous fix, if we find an operation with multiple success responses but different mappers we throw an error as we don't  support that scenario yet.
2. There can be collisions between Response type names and properties inside the response. For example this …
> [v6] Fix duplicate mappers and Response type name collisions

- package-lock.json
- package.json
- src/azure/Model/PageCompositeTypeTSa.cs
Fixes #615 
Make sure that the interface also extends the base model when generating PageCompositeTypes.
For example in [this swagger](https://github.com/Azure/azure-rest-api-specs/blob/0c0880833da9d695140d140071aea579fdc3da38/specification/recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices/stable/2019-06-15/bms.json#L3610-L3627) `ResourceList` is dropped when generating `JobResourceList`
```typescript
export interface JobResourceList extends Array<JobResource> {
}
```
Where it should generate the following in order to honor the swagger definition
```typescript
export interface JobResourceList extends Array<JobResource>, JobResourceList {
}
```
@daviwil, @sarangan12  - let me know if you think this is a good approach for fixing this issue
> [v5] Keep parents when generating PageCompositeTypes

- package-lock.json
- package.json
- src/vanilla/ClientModelExtensions.cs
- src/vanilla/Model/CodeModelTS.cs
- test/vanilla/generated/XMSErrorResponses/models/mappers.ts
In short the problem seems to be in the way we currently figure out the `uberParent` when building the `discriminators` object, which is used by `core-http` to select the mapper to use for serialization.
This `discriminators` object is a dictionary with key `{uberParent}.{discriminatorValue}` and a Mapper  as a value. When dealing with an operation `core-http` knows the `uberParent` or `base` object and needs to figure out which descendant it is dealing with at run time based on the value of a property defined as `discriminator` in the `uberParent`.
So the problem seems to be that in Autorest we're building the dictionary and assume that always the **topLevel parent** is the one which defines the polymorphic discriminator. However this is not always true. We could have this hierarchy
In …
> [v4x] Polymorphic uber parent

- src/transforms/transforms.ts
Instead of using `codeModel.info.title` use language metadata to leverage M4 pre-namer.
Fixes #673 which is caused by info.title containing `()` and not correctly normalizing for use as ClassName.
> [v6]  Use CodeModel language metadata for Client Name

- src/generators/operationGenerator.ts
- src/transforms/parameterTransforms.ts
- test/integration/generated/azureParameterGrouping/src/models/parameters.ts
- test/integration/generated/modelFlattening/src/models/parameters.ts
- test/integration/generated/paging/src/models/parameters.ts
- test/integration/generated/xmlservice/src/operations/xml.ts
- test/smoke/generated/web-resource-manager/src/operations/webApps.ts
2 issues surfaced when working with Tables Swagger
1.  If an operation group contains both XML and non-XML operations, a serializer is instantiated with isXml parameter **true**. This confuses our serialization/deserialization when handling a non-XML operation spec. **Fix:** Create an additional xmlSerializer to use with Xml operationSpecs
2. optional grouped parameters need to have "options" part in the ParameterPath since we group them in "options", otherwise the serializer won't find it.
Fixes #692
> [v6] Separate Xml serializer and fix optional grouped parameters

- src/generators/modelsGenerator.ts
- src/utils/nameUtils.ts
requestOptions parameter name can collide with core-http's OperationOptions. Making it a reserved workd
> [v6] Make requestOptions a parameter reseved name

- src/generators/modelsGenerator.ts
- src/models/unionDetails.ts
- src/transforms/transforms.ts
- test/smoke/generated/arm-package-deploymentscripts-2019-10-preview/temp/arm-package-deploymentscripts-2019-10-preview.api.json
- test/smoke/generated/arm-package-features-2015-12/temp/arm-package-features-2015-12.api.json
- test/smoke/generated/arm-package-links-2016-09/temp/arm-package-links-2016-09.api.json
- test/smoke/generated/arm-package-locks-2016-09/temp/arm-package-locks-2016-09.api.json
- test/smoke/generated/arm-package-managedapplications-2018-06/temp/arm-package-managedapplications-2018-06.api.json
- test/smoke/generated/arm-package-policy-2019-09/temp/arm-package-policy-2019-09.api.json
- test/smoke/generated/arm-package-resources-2019-08/temp/arm-package-resources-2019-08.api.json
- test/smoke/generated/arm-package-subscriptions-2019-06/temp/arm-package-subscriptions-2019-06.api.json
- test/smoke/generated/compute-resource-manager/temp/compute-resource-manager.api.json
- test/smoke/generated/cosmos-db-resource-manager/temp/cosmos-db-resource-manager.api.json
- test/smoke/generated/graphrbac-data-plane/temp/graphrbac-data-plane.api.json
- test/smoke/generated/keyvault-resource-manager/temp/keyvault-resource-manager.api.json
- test/smoke/generated/monitor-data-plane/temp/monitor-data-plane.api.json
- test/smoke/generated/msi-resource-manager/temp/msi-resource-manager.api.json
- test/smoke/generated/network-resource-manager/temp/network-resource-manager.api.json
- test/smoke/generated/sql-resource-manager/temp/sql-resource-manager.api.json
- test/smoke/generated/storage-resource-manager/temp/storage-resource-manager.api.json
- test/smoke/generated/web-resource-manager/temp/web-resource-manager.api.json
- test/unit/transforms/transforms.spec.ts
This PR is Part I of PRs to support issue https://github.com/Azure/autorest.typescript/issues/718. 
If the swagger mentions customized names for each enum value (thru x-ms-enum options), then we need to support it in our generator. How are we going to support it? Is it through classes with static properties/enum values/some other option? That is a seperate discussion and will be covered in the next set of PRs. 
However, before we decide the method to handle the names, we need to be able to access the names in the transformed code model (which will be passed to the model generator). This PR is to handle that issue. 
@josecons-msft @daviwil Please review and approve.
@ramya-rao-a FYI....
> [v6] Better support for x-ms-enum - Part I

- src/transforms/mapperTransforms.ts
OpenAPI specification supports [XML namespace and prefix](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#fixed-fields-22), however our generator doesn't and just ignores these properties. This PR picks up the metadata and exposes it in the mappers for `@azure/core-http` to do the required serialization.
Here's a [link ](https://github.com/Azure/azure-sdk-for-js/pull/11201)for core-http's PR
> [v6] Support xmlNamespace and xmlPrefix

- src/generators/modelsGenerator.ts
- src/utils/nameUtils.ts
- test/integration/bodyComplex.spec.ts
- test/integration/generated/bodyComplex/src/models/index.ts
- Adding test coverage
- Remove duplicate unwanted property in generated models
- When extracting polymorphic properties we need to remove the extracted one from the original property list to avoid duplicate properties
Closes #507
> Add missing tests for polymorphism

- test/integration/httpInfrastructure.spec.ts
2 Redirect tests were disabled because of https://github.com/Azure/azure-sdk-for-js/issues/10103
This PR enables them as a fix for the original bug is in PR https://github.com/Azure/azure-sdk-for-js/pull/11863
This was tested with a local build of the changes in the core-http PR above
> Enable redirect tests

- src/generators/modelsGenerator.ts
- test/integration/generated/bodyComplex/src/models/index.ts
- test/integration/generated/xmsErrorResponses/src/models/index.ts
- test/smoke/generated/arm-package-deploymentscripts-2019-10-preview/review/arm-package-deploymentscripts-2019-10-preview.api.md
- test/smoke/generated/arm-package-deploymentscripts-2019-10-preview/src/models/index.ts
- test/smoke/generated/arm-package-deploymentscripts-2019-10-preview/temp/arm-package-deploymentscripts-2019-10-preview.api.json
- test/smoke/generated/arm-package-deploymentscripts-2019-10-preview/temp/arm-package-deploymentscripts-2019-10-preview.api.md
- test/smoke/generated/graphrbac-data-plane/review/graphrbac-data-plane.api.md
- test/smoke/generated/graphrbac-data-plane/src/models/index.ts
- test/smoke/generated/graphrbac-data-plane/temp/graphrbac-data-plane.api.json
- test/smoke/generated/graphrbac-data-plane/temp/graphrbac-data-plane.api.md
- test/smoke/generated/network-resource-manager/review/network-resource-manager.api.md
- test/smoke/generated/network-resource-manager/src/models/index.ts
- test/smoke/generated/network-resource-manager/temp/network-resource-manager.api.json
- test/smoke/generated/network-resource-manager/temp/network-resource-manager.api.md
Only include the base class in the union type if the polymorphic parent's name is a valid discriminator value.
> Only add polymorphic parent to union if the parent is a valid value

- test/integration/mediaType.spec.ts
Enabling skipped missing type for MediaType tests. This scenario is supposed to test that Content-Type can be overriden, we can do that by passing customHeaders in the options parameter. See https://github.com/Azure/autorest.testserver/pull/228 for a conversation about the expectations of the test.
> Enable MediaType test scenario

- package-lock.json
- package.json
- test/integration/httpInfrastructure.spec.ts
Adding missing scenarios for the HTTP response tests. Found an issue in `core-http` which treats any statusCode that is not defined in the swagger as a success when there is no "default" status code. This will be fixed by https://github.com/Azure/azure-sdk-for-js/pull/12153
> Http Responses add missing test scenarios

- src/generators/utils/parameterUtils.ts
- test/smoke/generated/web-resource-manager/review/web-resource-manager.api.md
- test/smoke/generated/web-resource-manager/src/webSiteManagementClient.ts
- test/smoke/generated/web-resource-manager/temp/web-resource-manager.api.json
- test/smoke/generated/web-resource-manager/temp/web-resource-manager.api.md
**Problem**
We're including the original parameter that got flattened in the operation signature for paging operations
**Fix:**
Filter out parameters marked as flattened when getting the signature parameters
> Exclude flattened parameters from method signature

- src/generators/clientContextFileGenerator.ts
- test/integration/azureSpecialProperties.spec.ts
- test/integration/bodyComplex.spec.ts
- test/integration/generated/lro/src/lROClientContext.ts
- test/integration/generated/lroParametrizedEndpoints/src/lroParametrizedEndpointsClientContext.ts
- test/integration/generated/mediaTypesV3Lro/src/mediaTypesV3LROClientContext.ts
- test/integration/generated/paging/src/pagingClientContext.ts
- test/integration/generated/pagingNoIterators/src/pagingNoIteratorsClientContext.ts
- test/integration/lro.spec.ts
- test/smoke/generated/arm-package-deploymentscripts-2019-10-preview/src/deploymentScriptsClientContext.ts
- test/smoke/generated/arm-package-managedapplications-2018-06/src/applicationClientContext.ts
- test/smoke/generated/arm-package-resources-2019-08/src/resourceManagementClientContext.ts
- test/smoke/generated/compute-resource-manager/src/computeManagementClientContext.ts
- test/smoke/generated/cosmos-db-resource-manager/src/cosmosDBManagementClientContext.ts
- test/smoke/generated/keyvault-resource-manager/src/keyVaultManagementClientContext.ts
- test/smoke/generated/network-resource-manager/src/networkManagementClientContext.ts
- test/smoke/generated/sql-resource-manager/src/sqlManagementClientContext.ts
- test/smoke/generated/storage-resource-manager/src/storageManagementClientContext.ts
- test/smoke/generated/web-resource-manager/src/webSiteManagementClientContext.ts
- test/utils/smoke-test-list.ts
They way we add LRO policy and honor policies passed in `options.requestPolicyFactories` is not reliable  as we effectively bypass the default policyFactories added by `core-http`, the reason for this is that passing requestPolicyFactories as an array of factories tells `core-http` to not try adding any of the default policies see [here](https://github.com/Azure/azure-sdk-for-js/blob/98d87615a511484ed797cb1b91102432e1b16e70/sdk/core/core-http/src/serviceClient.ts#L201).
The fix in this PR is to handle the 3 scenarios we can face when working with LRO and policies
1) We are given an array of policy factories by the user. In this scenario the user decides to provide a list of all the pipelines they want to have and `core-http` won't add any default pipelines. We append the LRO policy to the …
> Reliably add generated pipeline policies to default

- package-lock.json
- package.json
Otherwise, we will get the error in this log when adding a dependency for core-auth: https://dev.azure.com/azure-public/azsdk/_build/results?buildId=10244&view=logs&j=499e71a5-ab92-5cb7-8e77-9c19c2280f63&t=331a722e-d89d-5d12-1500-1d0f556ecaa0
```
node_modules/@azure/abort-controller/types/src/AbortController.d.ts(73,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@azure/abort-controller/types/src/AbortSignal.d.ts(40,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/@azure/abort-controller/types/src/AbortSignal.d.ts(46,16): error TS1086: An accessor cannot be declared in an ambient context.
```
core-auth depends on abort-controller and it is needed for the work on supporting TokenCredential in v4. For more information, …
> Use TypeScript v3.6.0 to be able to compile abort-controller

- test/xml/xmlTests.ts
`gulp test` throws this error in tests when used with ms-rest-js from this [PR](https://github.com/Azure/ms-rest-js/pull/410): https://dev.azure.com/azure-public/azsdk/_build/results?buildId=10260&view=logs&j=86a3e3bd-71b3-5ac8-ea13-11866678232f&t=0ef955d0-98d6-55ad-9cce-da5a10715e64:
```
1) typescript
XML client
should be able to abort a simple XML get:
AssertionError: expected 'REQUEST_SEND_ERROR' to equal 'REQUEST_ABORTED_ERROR'
+ expected - actual
-REQUEST_SEND_ERROR
+REQUEST_ABORTED_ERROR
at Context.<anonymous> (test/xml/xmlTests.ts:30:23)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
This PR fixes this race condition by asking the controller to abort before the request is sent.
> Fix a race condition in unit tests

- package-lock.json
- package.json
- src/main.ts
- src/transforms/optionsTransforms.ts
- src/transforms/transforms.ts
- src/typescriptGenerator.ts
- test/unit/transforms/optionsTransforms.spec.ts
This package was renamed when we moved it to the autorest monorepo
> Rename @azure-tools/autorest-extension-base dependency to new @autorest/extension-base pkg

- package-lock.json
- package.json
This PR is to fix the issue https://github.com/Azure/autorest.typescript/issues/869. 
The issue happens only with a previous version of autorest. Once you upgrade the version, this issue will be resolved. 
@joheredi Please review and approve.
@ramya-rao-a FYI......
> Upgrade Autorest dependency in package

- src/generators/modelsGenerator.ts
- test/integration/generated/polymorphicSkipNormalize/src/generated/index.ts
- test/integration/generated/polymorphicSkipNormalize/src/generated/mediaServicesClient.ts
- test/integration/generated/polymorphicSkipNormalize/src/generated/mediaServicesClientContext.ts
- test/integration/generated/polymorphicSkipNormalize/src/generated/models/index.ts
- test/integration/generated/polymorphicSkipNormalize/src/generated/models/mappers.ts
- test/integration/swaggers/MediaServices_polymorphic_skipNormalize.md
- test/utils/test-swagger-gen.ts
We currently have the ability to tell the generator to skip property name normalization by setting an M4 name override like the following 
```yaml
modelerfour:
naming:
override:
'@type': $DO_NOT_NORMALIZE$@type
```
However in some cases, such as the one in the example, when generating the object key is enclosed by quotes to make it a valid javascript property name. This was causing 2 issues
1. normalizeName wouldn't recognize the $DO_NOT_NORMALIZE$ token, as the overriden name would not start with $DO_NOT_NORMALIZE$ but "$DO_NOT_NORMALIZE$. So it normalized it anyway
2. When generating non-discriminated properties we are note wrapping the property name in quotes which while doesn't make any difference in the actual generated code it would make generation fail if the example above was used …
> Fix polymorphic skip normalization

- src/generators/modelsGenerator.ts
- test/integration/generated/appconfiguration/src/models/index.ts
- test/integration/generated/appconfigurationexport/src/models/index.ts
- test/integration/generated/arrayConstraints/src/models/index.ts
- test/integration/generated/attestation/src/models/index.ts
- test/integration/generated/bodyArray/src/models/index.ts
- test/integration/generated/bodyComplex/src/models/index.ts
- test/integration/generated/bodyComplexWithTracing/src/models/index.ts
- test/integration/generated/extensibleEnums/src/models/index.ts
- test/integration/generated/licenseHeader/src/models/index.ts
- test/integration/generated/lro/src/models/index.ts
- test/integration/generated/modelFlattening/src/models/index.ts
- test/integration/generated/noLicenseHeader/src/models/index.ts
- test/integration/generated/noMappers/src/models/index.ts
- test/integration/generated/noOperation/src/models/index.ts
- test/integration/generated/nonStringEnum/src/models/index.ts
- test/integration/generated/odataDiscriminator/src/models/index.ts
- test/integration/generated/operationgroupclash/src/models/index.ts
- test/integration/generated/optionalnull/src/models/index.ts
- test/integration/generated/paging/src/models/index.ts
- test/integration/generated/pagingNoIterators/src/models/index.ts
- test/integration/generated/petstore/src/models/index.ts
- test/integration/generated/polymorphicSkipNormalize/src/generated/models/index.ts
- test/integration/generated/readmeFileChecker/src/models/index.ts
- test/integration/generated/storageblob/src/models/index.ts
- test/integration/generated/textanalytics/src/models/index.ts
- test/integration/generated/xmlservice/src/models/index.ts
This pull request renamed the generated header comment for extensible enums
Before: `Know values supported by the service`
After: `Known values supported by the service`
It's a tiny change, but I feel like `Know values` isn't grammatically correct - if there's a reason it's set that way
feel free to let me know!
> Rename know to known in extensible enum header comment

- src/vanilla/Model/CodeModelTS.cs
- test/azuremetadata/generated/Lro/README.md
- test/custom-service-client-options/generated/Xml/README.md
- test/metadata/generated/BodyComplex/README.md
- test/multiapi/packages/multiapi-test-2017-10-01/README.md
- test/multiapi/packages/multiapi-test-2018-02-01/README.md
- test/multiapi/packages/multiapi-test/README.md
- test/skip-subtypes/generated/BodyComplex/README.md
- test/unit-tests-custom/generated/BodyString/README.md
- test/unit-tests-mocha/generated/BodyString/README.md
Updates the list of supported environments as per https://github.com/Azure/autorest.typescript/issues/1021 for the legacy code generator.
> Update supported environments in readme

- src/vanilla/Model/CodeModelTS.cs
- test/azuremetadata/generated/Lro/README.md
- test/custom-service-client-options/generated/Xml/README.md
- test/metadata/generated/BodyComplex/README.md
- test/skip-subtypes/generated/BodyComplex/README.md
- test/unit-tests-custom/generated/BodyString/README.md
- test/unit-tests-mocha/generated/BodyString/README.md
Fixes the issue surfaced in https://github.com/Azure/azure-sdk-for-js/pull/15791#discussion_r653862779.
> [V4] Fix node capitalization in readme

- src/lroImpl.ts
- test/integration/generated/lro/src/lroImpl.ts
- test/integration/generated/lroParametrizedEndpoints/src/lroImpl.ts
- test/integration/generated/mediaTypesV3Lro/src/lroImpl.ts
- test/integration/generated/paging/src/lroImpl.ts
- test/integration/generated/pagingNoIterators/src/lroImpl.ts
- test/smoke/generated/arm-package-deploymentscripts-2019-10-preview/src/lroImpl.ts
- test/smoke/generated/arm-package-managedapplications-2018-06/src/lroImpl.ts
- test/smoke/generated/arm-package-resources-2019-08/src/lroImpl.ts
- test/smoke/generated/compute-resource-manager/src/lroImpl.ts
- test/smoke/generated/cosmos-db-resource-manager/src/lroImpl.ts
- test/smoke/generated/keyvault-resource-manager/src/lroImpl.ts
- test/smoke/generated/network-resource-manager/src/lroImpl.ts
- test/smoke/generated/sql-resource-manager/src/lroImpl.ts
- test/smoke/generated/storage-resource-manager/src/lroImpl.ts
- test/smoke/generated/web-resource-manager/src/lroImpl.ts
Polling requests should not have bodies so this PR leaves out the requestBody part from the operation spec used to send the GET request. This PR also gives stronger types for the operation spec field in `lroImpl` class.
Fixes https://github.com/Azure/autorest.typescript/issues/1117
~TODO: regenerate all tests.~
@sarangan12 could you please bring this issue up in the code gen crew and see if folks agree on adding a route to the autorest test server to test this behavior?
> Polling Reqs should not have bodies

- src/generators/indexGenerator.ts
- src/restLevelClient/generateParameterTypes.ts
- src/restLevelClient/generateResponseTypes.ts
- src/restLevelClient/generateRestLevel.ts
- src/restLevelClient/getPropertySignature.ts
- src/restLevelClient/schemaHelpers.ts
- src/typescriptGenerator.ts
- test/integration/bodyStringRest.spec.ts
- test/integration/generated/bodyComplexRest/src/index.ts
- test/integration/generated/bodyComplexRest/src/models.ts
- test/integration/generated/bodyComplexRest/src/parameters.ts
- test/integration/generated/bodyStringRest/src/index.ts
- test/integration/generated/bodyStringRest/src/parameters.ts
- test/integration/generated/bodyStringRest/src/responses.ts
- test/integration/generated/multipleInheritanceRest/src/index.ts
- test/integration/generated/multipleInheritanceRest/src/parameters.ts
Adding test coverage for body string and making the following changes to the generator:
1. Generate index.ts
2. generate byteArray schemas as strings and add documentation to tell customers that the value may contain a base64 encoded string. We are not making it a Uint8Array because there is no good way to deserialize these strings without using some kind of mappers. We have decided to keep runtime thin and hand off that responsibility to the user, the SDK will return the value that the service returns, plus extra documentation to hint the user about the possible contents.
> [RLC] Add test coverage for body string

- src/restLevelClient/generateResponseTypes.ts
Generator builds the Header interfaces but never actually generates them
> [RLC] Generate missing header interfaces

- src/typescriptGenerator.ts
- test/integration/generated/operationgroupclash/src/models/index.ts
- test/integration/generated/operationgroupclash/src/operationGroupClashClient.ts
- test/integration/generated/operationgroupclash/src/operations/index.ts
- test/integration/generated/operationgroupclash/src/operations/pipelineOperations.ts
- test/integration/generated/operationgroupclash/src/operationsInterfaces/index.ts
- test/integration/generated/operationgroupclash/src/operationsInterfaces/pipelineOperations.ts
- test/integration/swaggers/operationGroupClash.json
pipeline is a member of core-client's ServiceClient. If a swagger defines an operation group named Pipeline we'd get a collision and a build error.
This PR reserves the Pipeline name and suffixes any operation group named pipeline with `Operations` as all other collisions are handled.
> Reserve pipeline client member

- src/generators/modelsGenerator.ts
- test/integration/generated/sealedchoice/src/models/index.ts
- test/integration/generated/sealedchoice/src/models/mappers.ts
- test/integration/swaggers/sealedchoice.json
This PR is to fix the issue reported in https://github.com/Azure/autorest.typescript/issues/1159. The Swagger has a sealed choice object such as:
```
"count": {
"type": "integer",
"format": "int32",
"enum": [ 1, 3, 5 ],
"x-ms-enum": {
"name": "Count",
"modelAsString": false
},
"description": "Number of masters (VMs) in the container service cluster. Allowed values are 1, 3, & 5.The default value is 1.",
"default": 1
}
```
The above swagger generates the following SDK code:
`export type Count = One | Three | Five;`
But it should be 
`export type Count = 1 | 3 | 5;`
This is happening because for Non-String Enum Values, the generator uses the `name` instead of `value`. This PR fixes it.
@joheredi Please approve it.
> Fix Non String Sealed Choices Generated Code

- src/transforms/mapperTransforms.ts
- test/integration/generated/bodyComplex/src/models/mappers.ts
- test/integration/generated/bodyComplexWithTracing/src/models/mappers.ts
- test/integration/generated/odataDiscriminator/src/models/mappers.ts
Recently, a customer reported an issue with the `search-documents` SDK. The problem is that while they are using the types with Discriminators, only the parent type is getting accessed. So, the properties that are specific to the child type are ignored and not sent to the service side. 
On analysis, I have found that the issue is because of the problem with the property `clientName`. We have 2 properties:
1. clientName
2. serializedName
As of now, both the properties are set to same value. That was not the intention of the 2 properties and is incorrect. If you look at the code within `core-http` (where these values are getting used), it is clear that the property `clientName` should indicate the `name` that is used on the client/SDK side. 
This PR has been created to fix the issue and set …
> Fix the value of clientName Property in the Discriminators

- test/integration/azureSpecialProperties.spec.ts
We can re-enable AzureSpecialPRoperties tests by temporarly removing the bearerTokenPolicy. There is no need to skip all tests but the first one
> Reenable azureSpecialProperties tests

- src/transforms/objectTransforms.ts
- src/transforms/transforms.ts
- test/integration/generated/arrayConstraints/src/models/index.ts
- test/integration/generated/arrayConstraints/src/models/mappers.ts
- test/integration/swaggers/arrayConstraints.json
- test/integration/swaggers/arrayConstraints.md
- test/utils/test-swagger-gen.ts
This PR is created to fix the issue reported in https://github.com/Azure/autorest.typescript/issues/1185.  
**What is the problem?**
Let us assume the following swagger definition:
```json
"custom": {
"description": "The OS of agent machine",
"enum": ["Windows", "Linux"],
"type": "string",
"x-ms-enum": {
"name": "OS",
"modelAsString": true
}
}
```
Here, if you look at the `name` of the `x-ms-enum`, it is `OS`. But, it gets normalized during the SDK generation and gets converted to `Os` at the time interface creation. But, the same name is used at the place it is referenced. i.e:
```
export interface Product {
integer?: number;
string?: string;
/** The OS of agent machine */
custom?: OS;
}
export type Os = string;
```
As a result, we get build errors. This error muse be fixed. 
**How …
> Normalize only the required properties

- src/generators/static/readmeFileGenerator.ts
Solves https://github.com/Azure/autorest.typescript/issues/1213
If the generated package is a preview version, the API reference docs URL contains `?view=azure-node-preview` at the end. To determine if a package is a preview SDK it looks for the keyword `preview` or `beta` on the package version.
Tested this change by manually modifying the `const package_version` and `packageName` to add `@azure` in _test-swagger-gen.ts_. These changes were not committed.
> Reference docs links for preview packages

- test/integration/generated/lroRest/src/parameters.ts
- test/integration/generated/mediaTypesRest/src/mediaTypes.ts
- test/integration/generated/mediaTypesRest/src/parameters.ts
- test/integration/generated/mediaTypesRest/src/responses.ts
- test/integration/lroRest.spec.ts
- test/integration/mediaTypesRest.spec.ts
- test/integration/pagingRest.spec.ts
- test/integration/urlRest.spec.ts
There were a couple of issues from the last 2 PRs
1. There was an unresolved merge conflict that caused a couple of RLC tests to be outdated. Re-generating fixes this issue.
2. Accidentally the urlRest tests added a `.only` in their describe, which skips all other tests in the suite. This hid a few issues that came up when upgrading to the latest @azure-rest/core-client. Updated the tests to align with the changes, which were
2.1 core-client-rest now throws when the response has application/json content-type but it is an invalid JSON
2.2 We are now encoding the URL, so one of the LRO tests needed to set skipUrlEncoding property.
2.3 Media Types REST PDF test fails, I have filed an issue to investigate and fix in a separate PR
> Update generated tests and remove `.only` in url tests

- azure-pipelines.yml
It looks like the vminage was discontinued, updating it and moving the ci file to the .scripts folder to match the main branch
> [v4x] Fix CI

- docs/contributing.md
Updates the section on updating dependencies in generated SDK with a pointer to an example
> Add an example for updating dependency

- src/restLevelClient/generateClientDefinition.ts
- test/integration/generated/bodyComplexRest/src/clientDefinitions.ts
- test/integration/generated/bodyFileRest/src/clientDefinitions.ts
- test/integration/generated/bodyFormDataRest/src/clientDefinitions.ts
- test/integration/generated/bodyStringRest/src/clientDefinitions.ts
- test/integration/generated/customUrlRest/src/clientDefinitions.ts
- test/integration/generated/headerRest/src/clientDefinitions.ts
- test/integration/generated/lroRest/src/clientDefinitions.ts
- test/integration/generated/mediaTypesRest/src/clientDefinitions.ts
- test/integration/generated/multipleInheritanceRest/src/clientDefinitions.ts
- test/integration/generated/pagingRest/src/clientDefinitions.ts
- test/integration/generated/urlRest/src/clientDefinitions.ts
- test/smoke/generated/agrifood-data-plane/src/clientDefinitions.ts
- test/smoke/generated/purview-administration-rest/src/account/clientDefinitions.ts
- test/smoke/generated/purview-administration-rest/src/metadataPolicies/clientDefinitions.ts
- test/smoke/generated/synapse-artifacts-rest/src/clientDefinitions.ts
- test/version-tolerance/generated/llc-initial/src/clientDefinitions.ts
- test/version-tolerance/generated/llc-updated/src/clientDefinitions.ts
fix https://github.com/Azure/autorest.typescript/issues/1293
Issue description: The generated `clientDefinitions` contains credential related import, which is not used in the generated file `clientDefinions.ts`. The unused import leads to build failure when we build it by using azure-sdk-for-js 's tsconfig.
> remove unused import in clientDefinitions

- src/autorestSession.ts
- src/generators/indexGenerator.ts
- src/restLevelClient/generateClient.ts
- src/restLevelClient/generateTopLevelIndexFile.ts
- src/utils/autorestOptions.ts
- test/smoke/swagger/purview-administration-rest.md
- test/utils/smoke-test-list.ts
This PR adds a new flag `multi-client` to represents it's generating multi clients.
Previously, codegen generates multi clients when `batch` task is set. However, if we only want to use `batch` task to generate multi packages, it's no way. So we need a new flag `multi-client` to indicate codegen is generating multi client.
> [RLC] add new flag multi-client

- src/transforms/samplesTransforms.ts
to remove the import of Record<string, unknown> if the body schema type is any object in sample generation
> fix-any-object-body-parameter-for-sample-generation

- package-lock.json
- package.json
The last 2 vulnerabilities of the @autorest/typescript package will be removed with this PR. The package `@autorest/test-server` looks like an old and obsolete package that we do not use anymore. So, it is safe to remove it.
@joheredi Please review and approve the PR
> Remove @autorest/test-server dependency

- .scripts/ci.yml
- .scripts/globals.yml
- .scripts/smoke-test.yml
While working on the Component Governance Issues, I have noticed that the Component Detection Job is run at every stage (Build, HLC Test, RLC Test, Smoke Test, Unit Test). This is not only time cosuming and unnecessary. Sometime, when it hangs it will create a component governance violations  that are not there. 
@praveenkuttappan suggested to remove the component governance from all steps other than build. This PR is to do that. You can see a test run here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1524546&view=logs&j=462ec23f-14a8-561c-bd2a-3cc23815db36 - This one has Component Governance only under the Build Stage 
Compare it with the old run - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1524441&view=logs&j=88cef286-44ca-5c67-b516-cbd63d8b0608 …
> Remove Component Det from Test Stages

- src/generators/static/rlcREADME.md.hbs
- test/rlcIntegration/generated/bodyComplexRest/README.md
- test/rlcIntegration/generated/bodyFileRest/README.md
- test/rlcIntegration/generated/bodyFormDataRest/README.md
- test/rlcIntegration/generated/bodyStringRest/README.md
- test/rlcIntegration/generated/customUrlRest/README.md
- test/rlcIntegration/generated/dpgCustomization/README.md
- test/rlcIntegration/generated/headerRest/README.md
- test/rlcIntegration/generated/httpInfrastructureRest/README.md
- test/rlcIntegration/generated/lroRest/README.md
- test/rlcIntegration/generated/mediaTypesRest/README.md
- test/rlcIntegration/generated/multipleInheritanceRest/README.md
- test/rlcIntegration/generated/pagingRest/README.md
- test/rlcIntegration/generated/urlRest/README.md
- test/smoke/generated/agrifood-data-plane/README.md
- test/smoke/generated/purview-administration-rest/README.md
- test/unit/generators/static/files/case-rlcReadme.md
Fix the wrong links in rlc README.md. These links are related to authentication.
> Fix the wrong links in rlc README.md

- src/generators/static/packageFileGenerator.ts
- test/rlcIntegration/generated/bodyComplexRest/package.json
- test/rlcIntegration/generated/bodyFileRest/package.json
- test/rlcIntegration/generated/bodyFormDataRest/package.json
- test/rlcIntegration/generated/bodyStringRest/package.json
- test/rlcIntegration/generated/customUrlRest/package.json
- test/rlcIntegration/generated/dpgCustomization/package.json
- test/rlcIntegration/generated/headerRest/package.json
- test/rlcIntegration/generated/httpInfrastructureRest/package.json
- test/rlcIntegration/generated/lroRest/package.json
- test/rlcIntegration/generated/mediaTypesRest/package.json
- test/rlcIntegration/generated/multipleInheritanceRest/package.json
- test/rlcIntegration/generated/pagingRest/package.json
- test/rlcIntegration/generated/urlRest/package.json
- test/smoke/generated/agrifood-data-plane/package.json
- test/smoke/generated/purview-administration-rest/package.json
Moving from "dev" to the latest released core-client-rest
> [RLC] Update latest core-client-rest

- src/transforms/samplesTransforms.ts
This PR is trying to fix the sample generation error of Dictionary body object. 
Previously, the generated samples will try to import the Dictionary type from generated package like this 
```
import {
{ [propertyName: string]: any }
} from "@azure/arm-datafactory"
```
which is incorrect
> fix-dictionary-type-sample-generation-bug

- package.json
- src/utils/copyFiles.ts
A few weeks back, I was working on resolving the Audit Issues reported for the `autorest.typescript` repository. At that time, the package had a dependency on the `copyfiles` package which had a security vulnerability and thus have to be removed. So, I removed that and just used the regular `cp` command. It was working fine on my (windows) machine. 
But, now I have found that the `cp` was working fine on my machine, because I had the git bash installed. It was causing errors on other machines, where git bash was not installed. So, with this PR, I have replaced the `cp` command with a separate script. 
@joheredi Please review and approve the PR
> Replace Copy command with a script

- common/config/rush/pnpm-lock.yaml
- packages/autorest.typescript/package.json
- packages/autorest.typescript/test/integration/generated/paging/src/models/index.ts
- packages/autorest.typescript/test/integration/generated/paging/src/models/mappers.ts
- packages/autorest.typescript/test/integration/generated/paging/src/models/parameters.ts
- packages/autorest.typescript/test/integration/generated/paging/src/operations/paging.ts
- packages/autorest.typescript/test/integration/generated/paging/src/operationsInterfaces/paging.ts
- packages/autorest.typescript/test/integration/generated/pagingNoIterators/src/models/index.ts
- packages/autorest.typescript/test/integration/generated/pagingNoIterators/src/models/mappers.ts
- packages/autorest.typescript/test/integration/generated/pagingNoIterators/src/models/parameters.ts
- packages/autorest.typescript/test/integration/generated/pagingNoIterators/src/operations/paging.ts
- packages/autorest.typescript/test/integration/generated/pagingNoIterators/src/operationsInterfaces/paging.ts
- packages/autorest.typescript/test/integration/lro.spec.ts
- packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/src/clientDefinitions.ts
- packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/src/index.ts
- packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/src/isUnexpected.ts
- packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/src/models.ts
- packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/src/parameters.ts
- packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/src/responses.ts
- packages/autorest.typescript/test/rlcIntegration/lroRest.spec.ts
- packages/autorest.typescript/test/utils/cookies.ts
- packages/autorest.typescript/test/utils/responseStatusChecker.ts
There are two issues introduced when we upgrade the current dependencies and we'll try to fix in this pr.
fixes https://github.com/Azure/autorest.typescript/issues/1511
fixes https://github.com/Azure/autorest.typescript/issues/1544
@joheredi @deyaaeldeen I closed previous pr and reopen this one based on main branch. I updated the core-lro to 2.4.0 and  upgraded other packages to the latest. And fixed test case failures in ci and above issues.
However I didn't change any codegen logic especially relevant to lro option and I plan to do it in this [issue](https://github.com/Azure/autorest.typescript/issues/1598) once your existing lro prs merge into main.
> Update dependencies to the latest

- packages/autorest.typescript/test/rlcIntegration/generated/bodyStringRest/package.json
- packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/package.json
- packages/autorest.typescript/test/smoke/generated/anomaly-detector-rest/package.json
- packages/cadl-rlc-test/test/anomalyDetector/cadl-output/package.json
- packages/cadl-rlc-test/test/authoring/cadl-output/package.json
- packages/cadl-rlc-test/test/batch/cadl-output/package.json
- packages/cadl-rlc-test/test/confidentialLedger/cadl-output/package.json
- packages/cadl-rlc-test/test/customWrapper/cadl-output/package.json
- packages/cadl-rlc-test/test/multiclient/cadl-output/package.json
- packages/cadl-typescript/test/integration/generated/authentication/apiKey/package.json
- packages/rlc-common/src/metadata/buildPackageFile.ts
to be consistent with the azure-sdk-for-js repo
> Upgrade `nyc` to v15

- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/Account.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/Applications.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/Certificates.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/ComputeNodeExtensions.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/ComputeNodes.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/File.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/Job.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/JobSchedule.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/Pool.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/api/Task.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/rest/clientDefinitions.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/rest/isUnexpected.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/rest/parameters.ts
- packages/typespec-test/test/batch_modular/generated/typespec-ts/src/rest/responses.ts
- packages/typespec-test/test/batch_modular/spec/routes.tsp
- packages/typespec-ts/src/casingUtils.ts
- packages/typespec-ts/src/index.ts
- packages/typespec-ts/src/modular/buildOperations.ts
This PR adds support for generating operations. This will generate a file per operation spec. In case there is no operation specs defined in TypeSpec we will generate a single "operations.ts" file in which all operation will be generated.
> [Modular] Generate API operations

- .scripts/ci.yml
- .scripts/release.yml
Internal Azure SDK Engineering System update of the used Ubuntu image per
- https://github.com/Azure/azure-sdk-tools/issues/5472
I also searched for the other Ubuntu 18 strings as explained in [#5472](https://github.com/Azure/azure-sdk-tools/issues/5472) but did not find any.
> Update `azsdk-pool-mms-ubuntu-1804-general` to `azsdk-pool-mms-ubuntu-2004-general`

- .scripts/ci.yml
fixes ci failure: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2777974&view=logs&j=167756e8-11e6-5b09-f247-464e3cdd37fc&t=6e80cffa-694f-5c66-c385-ea5dadb8d133&l=31
```
ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session ca244b04-7122-40aa-89b9-88e5162c7eeb
##[error]Artifact CoverageReport already exists for build 2777974.
Finishing: Publish coverage report
```
> Only having one cadl-ranch cases

- .scripts/nightly.yml
- packages/typespec-ts/test/commands/cadl-ranch-list.ts
- packages/typespec-ts/test/unit/azureCoreOperationsGenerator.spec.ts
- packages/typespec-ts/test/unit/clientFactoryGenerator.spec.ts
- packages/typespec-ts/test/unit/modelsGenerator.spec.ts
- Remove the git check in smoke test considering we have false alarm for openapi changes
- Separate the Unit Test and Cadl-Ranch test in different jobs
- Fix the Unit Test failure found in nightly build
- add doc for enum or supress this warning
- Do not use the deprecation operation in core
```
2) Client Factory generation
should handle url parameters
should handle two parameters:
AssertionError [ERR_ASSERTION]: Unexpected diagnostics:
/test/main.tsp:33:15 - warning @azure-tools/typespec-azure-core/documentation-required: The EnumMember named 'V1' should have a documentation or description, please use decorator @doc to add it.
/test/main.tsp:34:15 - warning @azure-tools/typespec-azure-core/documentation-required: The EnumMember named 'V2' should have a documentation or description, …
```
> Fix nightly failure

- packages/autorest.typescript/src/restLevelClient/transforms/transformParameterTypes.ts
- packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/src/serializeHelper.ts
- packages/autorest.typescript/test/rlcIntegration/generated/urlRest/src/serializeHelper.ts
- packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/review/agrifood-data-plane.api.md
- packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/src/serializeHelper.ts
- packages/rlc-common/src/buildIndexFile.ts
- packages/rlc-common/src/buildSerializeHelper.ts
- packages/rlc-common/src/helpers/operationHelpers.ts
- packages/rlc-common/src/interfaces.ts
- packages/rlc-common/src/static/serializeHelper.ts
- packages/typespec-test/test/collectionFormat/generated/typespec-ts/review/collection-format.api.md
- packages/typespec-test/test/collectionFormat/generated/typespec-ts/src/serializeHelper.ts
- packages/typespec-test/test/translator/generated/typespec-ts/review/cognitiveservices-translator.api.md
- packages/typespec-test/test/translator/generated/typespec-ts/src/serializeHelper.ts
- packages/typespec-ts/src/transform/transformHelperFunctionDetails.ts
- packages/typespec-ts/src/transform/transformParameters.ts
- packages/typespec-ts/test/integration/collectionFormat.spec.ts
- packages/typespec-ts/test/integration/encode.spec.ts
- packages/typespec-ts/test/integration/generated/azure/core/src/serializeHelper.ts
- packages/typespec-ts/test/integration/generated/encode/src/parameters.ts
- packages/typespec-ts/test/integration/generated/encode/src/serializeHelper.ts
- packages/typespec-ts/test/integration/generated/parameters/collection-format/src/parameters.ts
- packages/typespec-ts/test/integration/generated/parameters/collection-format/src/serializeHelper.ts
When touching the collectionFormat integration cases we generate string[] for header with format defined, but I notice that `RawHttpHeadersInput` only allows for `string|number|boolean` which means there would exist type inference conflict for this property.
https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/core/core-rest-pipeline/src/interfaces.ts#L12-L15
To fix that we need to build a helper function for the default csv format for header.
> Fix collectionFormat issue in header

- packages/typespec-ts/src/transform/transformParameters.ts
- packages/typespec-ts/test/unit/parametersGenerator.spec.ts
Generate the datetime as `Date | string` when the parameter is in query & model property, as `string` in header.
> Fix the query datetime support issue

- packages/rlc-common/src/buildObjectTypes.ts
- packages/typespec-ts/src/utils/modelUtils.ts
- packages/typespec-ts/test/integration/generated/models/inheritance/src/models.ts
- packages/typespec-ts/test/integration/generated/models/inheritance/src/outputModels.ts
- packages/typespec-ts/test/integration/generated/specialWords/src/models.ts
- packages/typespec-ts/test/integration/generated/specialWords/src/outputModels.ts
- packages/typespec-ts/test/integration/modelInheritance.spec.ts
- packages/typespec-ts/test/unit/clientFactoryGenerator.spec.ts
- packages/typespec-ts/test/unit/modelsGenerator.spec.ts
- packages/typespec-ts/test/unit/util/emitUtil.ts
fixes https://github.com/Azure/autorest.typescript/issues/1922
> Support enum member as type

- packages/autorest.typescript/README.md
upgrade m4 version to 4.26.2 to support final-state-schema
> upgrade-m4-to-4.26.2 to support final state-schema

- packages/typespec-test/test/healthinsight/generated/typespec-ts/review/health-insights-clinicalmatching.api.md
- packages/typespec-test/test/healthinsight/generated/typespec-ts/src/responses.ts
- packages/typespec-ts/src/transform/transformResponses.ts
- packages/typespec-ts/src/transform/transformSchemas.ts
- packages/typespec-ts/src/utils/modelUtils.ts
- packages/typespec-ts/test/commands/cadl-ranch-list.ts
- packages/typespec-ts/test/integration/generated/dictionary/src/parameters.ts
- packages/typespec-ts/test/integration/generated/lro/lroRPC/src/responses.ts
- packages/typespec-ts/test/integration/generated/union-body/src/clientDefinitions.ts
- packages/typespec-ts/test/integration/generated/union-body/src/index.ts
- packages/typespec-ts/test/integration/generated/union-body/src/logger.ts
- packages/typespec-ts/test/integration/generated/union-body/src/models.ts
- packages/typespec-ts/test/integration/generated/union-body/src/outputModels.ts
- packages/typespec-ts/test/integration/generated/union-body/src/parameters.ts
- packages/typespec-ts/test/integration/generated/union-body/src/responses.ts
- packages/typespec-ts/test/integration/generated/union-body/src/unionBodyClient.ts
- packages/typespec-ts/test/integration/generated/union-body/tspconfig.yaml
- packages/typespec-ts/test/integration/typespec/union-body/main.tsp
- packages/typespec-ts/test/integration/unionBody.spec.ts
fixes https://github.com/Azure/autorest.typescript/issues/1926
> Support the request and response union body in rlc

- CONTRIBUTING.md
- packages/autorest.typescript/src/generators/static/packageFileGenerator.ts
- packages/autorest.typescript/test/integration/generated/additionalProperties/package.json
- packages/autorest.typescript/test/integration/generated/datasearch/package.json
- packages/autorest.typescript/test/integration/generated/patterntest/package.json
- packages/autorest.typescript/test/rlcIntegration/generated/bodyStringRest/package.json
- packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/package.json
- packages/autorest.typescript/test/smoke/generated/anomaly-detector-rest/package.json
- packages/autorest.typescript/test/smoke/generated/arm-package-subscriptions-2019-06/package.json
- packages/autorest.typescript/test/smoke/generated/compute-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/keyvault-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/msi-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/network-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/sql-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/storage-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/web-resource-manager/package.json
- packages/rlc-common/src/metadata/buildPackageFile.ts
- packages/typespec-test/test/anomalyDetector/generated/typespec-ts/package.json
- packages/typespec-test/test/authoring/generated/typespec-ts/package.json
- packages/typespec-test/test/collectionFormat/generated/typespec-ts/package.json
- packages/typespec-test/test/confidentialLedger/generated/typespec-ts/package.json
- packages/typespec-test/test/contoso/generated/typespec-ts/package.json
- packages/typespec-test/test/customWrapper/generated/typespec-ts/package.json
- packages/typespec-test/test/healthinsight/generated/typespec-ts/package.json
- packages/typespec-test/test/loadTest/generated/typespec-ts/package.json
- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/package.json
- packages/typespec-test/test/openai/generated/typespec-ts/package.json
- packages/typespec-test/test/translator/generated/typespec-ts/package.json
- packages/typespec-ts/test/integration/generated/authentication/apiKey/package.json
as tests relies on it to run .ts test files.
> Add `ts-node` to dev dependencies when generating tests

- packages/typespec-test/test/openai_modular/generated/typespec-ts/src/api/operations.ts
- packages/typespec-ts/src/modular/helpers/operationHelpers.ts
for comment https://github.com/Azure/autorest.typescript/pull/1975#discussion_r1297908714
> remove default value in Modular

- packages/typespec-ts/src/modular/buildCodeModel.ts
- packages/typespec-ts/src/modular/helpers/operationHelpers.ts
- packages/typespec-ts/src/modular/helpers/typeHelpers.ts
- packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts
fixes https://github.com/Azure/autorest.typescript/issues/2014
> fix-get-parent-properties

- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/review/load-testing.api.md
- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/loadTestAdministration/api/operations.ts
- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/loadTestAdministration/models/models.ts
- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/loadTestAdministration/models/options.ts
- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/loadTestRun/api/operations.ts
- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/loadTestRun/models/models.ts
- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/loadTestRun/models/options.ts
- packages/typespec-ts/src/modular/buildCodeModel.ts
- packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts
fix https://github.com/Azure/azure-sdk-for-js/pull/27087#issuecomment-1720020323
> use-string-as-offset-datetime-type-in-modular

- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/loadTestAdministration/api/operations.ts
- packages/typespec-ts/src/modular/buildCodeModel.ts
- packages/typespec-ts/src/modular/helpers/operationHelpers.ts
- packages/typespec-ts/src/modular/modularCodeModel.ts
- packages/typespec-ts/src/utils/modelUtils.ts
- packages/typespec-ts/test/modularIntegration/generated/encode/bytes/src/api/requestBody.ts
- packages/typespec-ts/test/modularIntegration/generated/encode/bytes/src/api/responseBody.ts
- packages/typespec-ts/test/modularUnit/apiOperations.spec.ts
> fix-default-byte-as-binary-payload-in-modular

- packages/autorest.typescript/src/utils/valueHelpers.ts
fix https://github.com/Azure/autorest.typescript/issues/2098
Special character can not be generated as a parameter name from sample generation, this pr is to fix this
> fix sample generation

- packages/typespec-ts/test/commands/cadl-ranch-list.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/RepeatabilityClient.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/api/RepeatabilityContext.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/api/index.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/api/operations.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/index.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/logger.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/models/index.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/models/options.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/rest/clientDefinitions.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/rest/index.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/rest/parameters.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/rest/repeatabilityClient.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/generated/src/rest/responses.ts
- packages/typespec-ts/test/modularIntegration/generated/headers/repeatability/tspconfig.yaml
- packages/typespec-ts/test/modularIntegration/headersRepeatability.spec.ts
fixes https://github.com/Azure/autorest.typescript/issues/2102
Added List:
1.headers-repeatability
> Add modular coverage cases for headers-repeatability in cadl-ranch

- packages/autorest.typescript/test/rlcIntegration/generated/bodyStringRest/package.json
- packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/package.json
- packages/autorest.typescript/test/smoke/generated/anomaly-detector-rest/package.json
- packages/rlc-common/src/metadata/buildPackageFile.ts
- packages/typespec-test/test/anomalyDetector/generated/typespec-ts/package.json
- packages/typespec-test/test/authoring/generated/typespec-ts/package.json
- packages/typespec-test/test/batch_modular/generated/typespec-ts/package.json
- packages/typespec-test/test/chatApi_modular/generated/typespec-ts/package.json
- packages/typespec-test/test/contoso/generated/typespec-ts/package.json
- packages/typespec-test/test/customWrapper/generated/typespec-ts/package.json
- packages/typespec-test/test/eventgrid_modular/generated/typespec-ts/package.json
- packages/typespec-test/test/healthinsight/generated/typespec-ts/package.json
- packages/typespec-test/test/hierarchy_generic/generated/typespec-ts/package.json
- packages/typespec-test/test/loadTest/generated/typespec-ts/package.json
- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/package.json
- packages/typespec-test/test/openai/generated/typespec-ts/package.json
- packages/typespec-test/test/openai_generic/generated/typespec-ts/package.json
- packages/typespec-test/test/openai_modular/generated/typespec-ts/package.json
- packages/typespec-test/test/overloads_modular/generated/typespec-ts/package.json
- packages/typespec-test/test/translator/generated/typespec-ts/package.json
- packages/typespec-test/test/widget_dpg/generated/typespec-ts/package.json
- packages/typespec-ts/src/modular/buildProjectFiles.ts
- packages/typespec-ts/test/integration/generated/authentication/apiKey/package.json
- packages/typespec-ts/test/integration/generated/authentication/http-custom/package.json
- packages/typespec-ts/test/integration/generated/azure/core-traits/package.json
- packages/typespec-ts/test/integration/generated/union-body/package.json
- It has been replaced with Mocha builtin XUnit reporter in Azure SDK for JavaScript repo in PR https://github.com/Azure/azure-sdk-for-js/pull/27992
- For non-azuresdkjs we don't currently use any mocha reporters in the command line.
> Remove `mocha-junit-reporter` dependency from generated packages

- common/config/rush/pnpm-lock.yaml
- packages/autorest.typescript/package.json
- packages/autorest.typescript/src/generators/static/packageFileGenerator.ts
- packages/autorest.typescript/test/integration/generated/useragentcorev1/package.json
to address security issue of pulling in older version of `xml2js` that contains vulnerability
> Upgrade core-http to 3.0.0

- common/config/rush/pnpm-lock.yaml
- packages/typespec-ts/package.json
- packages/typespec-ts/src/lib.ts
- packages/typespec-ts/src/utils/modelUtils.ts
- packages/typespec-ts/test/integration/generated/models/propertyTypes/src/clientDefinitions.ts
- packages/typespec-ts/test/integration/generated/models/propertyTypes/src/models.ts
- packages/typespec-ts/test/integration/generated/models/propertyTypes/src/outputModels.ts
- packages/typespec-ts/test/integration/generated/models/propertyTypes/src/parameters.ts
- packages/typespec-ts/test/integration/generated/models/propertyTypes/src/responses.ts
- packages/typespec-ts/test/integration/generated/scalar/src/clientDefinitions.ts
- packages/typespec-ts/test/integration/generated/scalar/src/parameters.ts
- packages/typespec-ts/test/integration/generated/scalar/src/responses.ts
- packages/typespec-ts/test/integration/modelPropertyType.spec.ts
- packages/typespec-ts/test/integration/scalar.spec.ts
- packages/typespec-ts/test/unit/modelsGenerator.spec.ts
- packages/typespec-ts/test/util/emitUtil.ts
fixes https://github.com/Azure/autorest.typescript/issues/2157 
Support decimal in RLC - map the decimal to `number` in JS directly, and will 
- add below comments in generated code
```
Please note the field was supposed to be a decimal but JavaScript does not have a native 'BigDecimal' data type.
So it was converted to a number instead. It is recommended to use a third-party library like 'decimal.js' to handle 
any calculations.
```
- report a warning 
```
Please note the decimal type will be converted to number. If you strongly care about precision you can use @encode to encode it as a string for the property - {your prop name}.
```
Encoding as string is still pending typespec discussion https://github.com/microsoft/typespec/issues/2762.
> Support decimal type in RLC

- common/config/rush/pnpm-lock.yaml
- packages/autorest.typescript/CHANGELOG.md
- packages/autorest.typescript/package.json
- packages/autorest.typescript/test/rlcIntegration/generated/dpgCustomization/package.json
- packages/autorest.typescript/test/rlcIntegration/generated/httpInfrastructureRest/package.json
- packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/package.json
- packages/autorest.typescript/test/rlcIntegration/generated/securityAADRest/package.json
- packages/autorest.typescript/test/rlcIntegration/generated/securityKeyRest/package.json
- packages/rlc-common/CHANGELOG.md
- packages/rlc-common/package.json
- packages/rlc-common/src/metadata/packageJson/buildAzureMonorepoPackage.ts
- packages/rlc-common/test/integration/packageJson.spec.ts
- packages/typespec-test/package.json
- packages/typespec-ts/CHANGELOG.md
- packages/typespec-ts/package.json
fixes https://github.com/Azure/autorest.typescript/issues/2403
> Fix missing scripts issue in package.json and bump emitter version

- packages/autorest.typescript/README.md
It appears that using `package-version` is already supported ([code](https://github.com/Azure/autorest.typescript/blob/cbe71a7d83ac6d0240fe99973ee94f7266191083/packages/typespec-ts/src/modular/buildCodeModel.ts#L134)) to set the `version` attribute in `package.json`, but not yet documented.
PR adds this to README.
> Document package-version in README.md

- packages/autorest.typescript/src/generators/static/packageFileGenerator.ts
- packages/autorest.typescript/test/integration/generated/additionalProperties/package.json
- packages/autorest.typescript/test/integration/generated/datasearch/package.json
- packages/autorest.typescript/test/integration/generated/patterntest/package.json
- packages/autorest.typescript/test/smoke/generated/arm-package-subscriptions-2019-06/package.json
- packages/autorest.typescript/test/smoke/generated/compute-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/keyvault-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/msi-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/network-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/sql-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/storage-resource-manager/package.json
- packages/autorest.typescript/test/smoke/generated/web-resource-manager/package.json
- packages/rlc-common/src/metadata/packageJson/buildAzureMonorepoPackage.ts
- packages/rlc-common/test/integration/packageJson.spec.ts
as we already switched to `tsx` in PR https://github.com/Azure/azure-sdk-for-js/pull/28826/files#diff-164a9ae95cf7571742ca1882b5fdc0a43e7000c271ff566de5e99ef2c2820021R34
and removed `esm` https://github.com/Azure/azure-sdk-for-js/commit/446e9d831bb77c8dec881c660c64df04384be45c
> Replace `esm` dev dependency with `tsx` for js mono repo

- packages/typespec-ts/test/integration/multipart.spec.ts
Add coverage for these cadl-ranch scenarios:
- `/multipart/form-data/anonymous-model`
- `/multipart/form-data/json-part`
Not adding coverage for array of JSON parts yet pending change in cadl-ranch and new TypeSpec multipart design.
> Extra cadl-ranch scenarios for multipart

- common/config/rush/pnpm-lock.yaml
- packages/typespec-ts/package.json
- packages/typespec-ts/src/modular/serialization/operationHelpers.ts
- packages/typespec-ts/test-next/serialization/operationHelper.test.ts
- packages/typespec-ts/test-next/serialization/util.test.ts
- packages/typespec-ts/tsconfig.json
- packages/typespec-ts/vitest.config.ts
Keeping these tests under test-next since they are true unit test. Will consolidate later when re-organizing the tests. Using vitest for new unit tests since it has better support for ESModules
> Add unit tests for serializer

- packages/rlc-common/src/buildClient.ts
- packages/typespec-test/test/openai_generic/generated/typespec-ts/src/rest/openAIClient.ts
- packages/typespec-test/test/openai_non_branded/generated/typespec-ts/src/rest/openAIClient.ts
- packages/typespec-test/test/todo_non_branded/generated/typespec-ts/src/todoClient.ts
- packages/typespec-ts/src/transform/transfromRLCOptions.ts
- packages/typespec-ts/test/unit/clientFactoryGenerator.spec.ts
fixes https://github.com/Azure/autorest.typescript/issues/2572 
fixes https://github.com/Azure/autorest.typescript/issues/2109
> Update `bearer` to `Bearer`

- packages/autorest.typescript/test/rlcIntegration/generated/dpgCustomization/src/pollingHelper.ts
- packages/autorest.typescript/test/rlcIntegration/generated/lroRest/src/pollingHelper.ts
- packages/autorest.typescript/test/rlcIntegration/generated/pagingRest/src/pollingHelper.ts
- packages/autorest.typescript/test/smoke/generated/agrifood-data-plane/src/pollingHelper.ts
- packages/autorest.typescript/test/smoke/generated/anomaly-detector-rest/src/pollingHelper.ts
- packages/autorest.typescript/test/smoke/generated/synapse-artifacts-rest/src/pollingHelper.ts
- packages/rlc-common/src/static/pollingContent.ts
- packages/typespec-test/test/NetworkAnalytics.Management/generated/typespec-ts/src/rest/pollingHelper.ts
- packages/typespec-test/test/authoring/generated/typespec-ts/src/pollingHelper.ts
- packages/typespec-test/test/contoso/generated/typespec-ts/src/pollingHelper.ts
- packages/typespec-test/test/faceai/generated/typespec-ts/src/pollingHelper.ts
- packages/typespec-test/test/healthInsights_radiologyinsights/generated/typespec-ts/src/pollingHelper.ts
- packages/typespec-test/test/healthInsights_trialmatcher/generated/typespec-ts/src/pollingHelper.ts
- packages/typespec-test/test/loadTest/generated/typespec-ts/src/pollingHelper.ts
- packages/typespec-test/test/loadtesting_modular/generated/typespec-ts/src/rest/pollingHelper.ts
- packages/typespec-test/test/openai/generated/typespec-ts/src/pollingHelper.ts
- packages/typespec-test/test/widget_dpg/generated/typespec-ts/src/rest/pollingHelper.ts
- packages/typespec-ts/test/integration/generated/azure/core/lro/rpc/src/pollingHelper.ts
- packages/typespec-ts/test/integration/generated/azure/core/lro/standard/src/pollingHelper.ts
- packages/typespec-ts/test/modularIntegration/generated/azure/core/lro/rpc/generated/src/rest/pollingHelper.ts
- packages/typespec-ts/test/modularIntegration/generated/azure/core/lro/standard/generated/src/rest/pollingHelper.ts
fixes https://github.com/Azure/azure-sdk-for-js/pull/30033
> Rename parameter name in pollingHelper to fix lint error

- packages/typespec-test/test/openai_generic/generated/typespec-ts/review/openai-generic.api.md
- packages/typespec-test/test/openai_generic/generated/typespec-ts/src/models/models.ts
- packages/typespec-test/test/openai_non_branded/generated/typespec-ts/review/openai-non-branded.api.md
- packages/typespec-test/test/openai_non_branded/generated/typespec-ts/src/models/models.ts
- packages/typespec-ts/src/modular/helpers/typeHelpers.ts
- packages/typespec-ts/test/modularUnit/typeHelpers.spec.ts
Hanld the nullable dictionary in modular.
fix the azure fleet build issue.
> Handle nullable dictionaries in modular

- packages/autorest.typescript/test/rlcIntegration/generated/dpgCustomization/tsconfig.json
- packages/autorest.typescript/test/rlcIntegration/generated/httpInfrastructureRest/tsconfig.json
- packages/autorest.typescript/test/rlcIntegration/generated/multipleUrlParameters/tsconfig.json
- packages/autorest.typescript/test/rlcIntegration/generated/securityAADRest/tsconfig.json
- packages/autorest.typescript/test/rlcIntegration/generated/securityKeyRest/tsconfig.json
- packages/rlc-common/src/metadata/buildTsConfig.ts
I plan to do the same for all packages in the Azure SDK for JS repository as the
latter just simply extends from the former. There might be more customization in
the early days but no longer the case.
> Extend from ../../../tsconfig instead of ../../../tsconfig.package

- .scripts/nightly.yml
Fix the nightly build failure in smoke test because of resource issue
the build is successful here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3976274&view=results
> Fix the nightly build failure in smoke test because of resource issue

- packages/typespec-ts/src/azure/dependency.ts
- packages/typespec-ts/src/contextManager.ts
- packages/typespec-ts/src/framework/dependency.ts
- packages/typespec-ts/src/framework/hooks/binder.ts
- packages/typespec-ts/src/framework/hooks/useDependencies.ts
- packages/typespec-ts/src/framework/reference.ts
- packages/typespec-ts/src/framework/sample.ts
- packages/typespec-ts/test-next/integration/hooks/binder.test.ts
- packages/typespec-ts/test-next/utils/tsmorph-utils.ts
Whit this change the binder supports:
* Referencing symbols from external dependencies
* There is a default set of dependencies that point to `@typespec/ts-http-runtime`
* Users can override these by providing a custom record with imports if they need to import from a different package.
**Referencing an external dependency (ClientOptions)**
```ts
import { Project } from "ts-morph"
import {provideBinder} from "../framework/binder.js";
import { addDeclaration } from "../framework/declaration.js";
import { resolveReference } from "../framework/reference.js";
const project = new Project();
provideBinder(project);
const binder = useBinder();
const Dependencies = useDependencies();
const sourceFile = project.createSourceFile("test1.ts", "", {
overwrite: true
});
const interfaceDeclaration: …
```
> Binder support external dependencies

- packages/typespec-test/test/loadtesting_modular/spec/client.tsp
Update with https://github.com/Azure/azure-rest-api-specs/pull/30005
Fix https://dev.azure.com/azure-sdk/public/_build/results?buildId=3993520&view=logs&j=830f3c89-f0a6-536d-4907-0d5f5b592ed8&t=df42c93f-8bab-5640-0499-96898203e019&l=33
> Fix invalid versioning in client.tsp

- packages/typespec-ts/src/modular/buildCodeModel.ts
- packages/typespec-ts/src/utils/modelUtils.ts
Monitor @typespec/compiler dev version build
https://dev.azure.com/azure-sdk/public/_build/results?buildId=4011943&view=logs&j=d0d2a462-287f-51d5-e186-98b6b49f577f
> Fix build error

- packages/autorest.typescript/src/utils/autorestOptions.ts
we should not require customers to set flavor: azure if the scope name is azure-rest.
> should-default-flavor-to-azure-for-rlc

- packages/typespec-ts/src/modular/helpers/operationHelpers.ts
- packages/typespec-ts/test/modularUnit/apiOperations.spec.ts
- packages/typespec-ts/test/modularUnit/modelsGenerator.spec.ts
fixes https://github.com/Azure/autorest.typescript/issues/2777
> Boolean literal type

- packages/rlc-common/src/metadata/packageJson/buildAzureMonorepoPackage.ts
- packages/rlc-common/test/integration/packageJson.spec.ts
Resolves https://github.com/Azure/azure-sdk-for-js/issues/31211
This PR updates the codegen for ESM packages within the monorepo to use the `build-package` command instead of using tshy directly.
The changes have been made in the azure-sdk-for-js repo, this PR ensures codegen behaves.
this is my first PR in the autorest.typescript repo so please do assume I forgot / missed something and let me know what was missed. I was surprised that smoke tests did not fail, but maybe there's a different command to run them
> [engsys] Use dev-tool command in tshy for monorepo

- packages/typespec-ts/src/index.ts
fixes https://github.com/Azure/autorest.typescript/issues/3077
1： if we manually set generateTest as false
emitter will not generate test folder and ralated dependencies and configs
2： if we don't set generate-test in tsconfig
it could generate test folder
> Improve generateTest config 

- packages/autorest.typescript/src/generators/static/packageFileGenerator.ts
- packages/rlc-common/src/metadata/buildPackageFile.ts
- packages/rlc-common/src/metadata/packageJson/buildAzureMonorepoPackage.ts
as we should use caret versions for dependencies on our @azure packages
> [pnpm migration] use "workspace:^"

- packages/autorest.typescript/src/generators/static/packageFileGenerator.ts
- packages/rlc-common/src/metadata/packageJson/buildAzureMonorepoPackage.ts
- packages/rlc-common/test/integration/mockHelper.ts
- packages/rlc-common/test/integration/packageJson.spec.ts
so that the "workspace:" version specifiers are replaced with real versions
> [pnpm migration] switch from "npm pack" to "pnpm pack"
